/**
 * Content Studio product configs — AI Pins vs AI Facebook Pages.
 * Same atelier UX; only network terminology + destination adapter differ.
 */

export const AI_PINS_PRODUCT = {
	id: 'ai-pins',
	featureFlag: 'pinterest',
	destinationId: 'pinterest',
	routes: {
		studio: '/app/ai-pins',
		history: '/app/ai-pins/history',
		connect: '/app/pinterest',
		publishingHistory: '/app/pinterest-history',
		templates: '/app/ai-pins/templates',
		brandKit: '/app/ai-pins/brand-kit',
	},
	labels: {
		platformName: 'Chef IA',
		atelierTitle: 'AI Pins Atelier',
		itemSingular: 'Pin',
		itemPlural: 'Pins',
		itemLower: 'pin',
		itemLowerPlural: 'pins',
		productShort: 'AI Pin',
		productShortPlural: 'AI Pins',
		account: 'Pinterest account',
		accountTitle: 'Pinterest Account',
		destination: 'Board',
		destinationLower: 'board',
		destinationPlural: 'boards',
		network: 'Pinterest',
		connectCta: 'Connect Pinterest',
		connectBannerTitle: 'Pin created — connect Pinterest next',
		connectBannerBody: 'Publishing requires a connected Pinterest account and board.',
		readyBanner: 'Pinterest is ready — publish your first pin to enter Operate Mode.',
		connectStudioHint: 'Connect Pinterest to publish pins from this studio.',
		sizeSection: 'Pinterest size',
		guidedSetup: (siteName) => `Create your first pin for ${siteName}, connect Pinterest, then publish to finish setup.`,
		operateSubtitle: (siteName) => (siteName
			? `Compose Pinterest-ready drafts for ${siteName} — then refine and publish.`
			: 'Compose Pinterest-ready drafts from pages, bulk catalogs, or free prompts — then refine and publish.'),
		generateStep: 'Step 3 — Generate Pins',
		generateOne: 'Generate Pin',
		generateMany: (n) => `Generate ${n} Pins`,
		emptyCanvas: 'Pick a mode on the left, tune quality and size, then generate. Previews appear here as tall Pinterest cards with live progress.',
		libraryEmpty: 'Select articles above, choose a template, and generate AI Pins. When ready, publish to Pinterest.',
		noDestination: 'No board',
		detailsTitle: 'Pin details',
		targetDestination: 'Target board',
		useGlobalDestination: 'Use global board',
		selectDestination: 'Select board',
		selectAccount: 'Select account',
		accountUnavailableTitle: 'Pinterest account unavailable',
		accountUnavailableBody: 'Reconnect this Pinterest account to load boards.',
		loadAccountsFailed: 'Failed to load Pinterest accounts',
		loadDestinationsFailed: 'Failed to load Pinterest boards',
		chooseAccount: 'Choose a target Pinterest account first.',
		chooseDestination: 'Choose a target Pinterest board.',
		accountNotFound: 'Pinterest account not found. Connect Pinterest first.',
		accountNotConnected: 'Pinterest account is not connected. Reconnect it in Pinterest settings.',
		analyzeDone: 'Pinterest metadata was generated from the article.',
		missingLink: 'Cannot generate pins without a destination link for Pinterest.',
		savedConnectNext: 'Next: connect Pinterest so you can publish.',
		savedPublishSetup: 'draft(s) ready. Next: publish to finish setup.',
		savedPublishOperate: 'draft(s) ready. Next: publish or schedule from the library.',
		publishedItem: 'Pin published',
		failedItem: 'Pin failed',
		draftTitleFallback: 'Draft AI Pin',
		scheduleTitle: (count) => `Schedule pin${count > 1 ? 's' : ''}`,
		scheduleSubtitle: (count) => `${count} pin${count === 1 ? '' : 's'} · appears on Calendar when scheduled`,
		previewTitle: 'Preview pin',
		progressNetworkLabel: 'Pinterest response',
		openOnNetwork: 'Open on Pinterest',
		externalIdLabel: 'Pin ID',
		historyNav: 'History',
		publishingHistoryNav: 'Publishing History',
		textOverlay: 'Pin text overlay',
		numberOfItems: 'Number of pins',
		itemStyle: 'Pin style',
		itemTitleSeed: 'Pin title seed',
		targetAccount: 'Target account',
	},
	studioAssets: {
		defaultExportProfileId: 'pinterest_standard',
		exportProfileIds: ['pinterest_standard'],
		templatePackKey: 'pinterest',
	},
};

export const AI_FACEBOOK_PAGES_PRODUCT = {
	id: 'ai-facebook-pages',
	featureFlag: 'facebook',
	destinationId: 'facebook',
	routes: {
		studio: '/app/ai-facebook-pages',
		history: '/app/ai-facebook-pages/history',
		connect: '/app/facebook',
		publishingHistory: '/app/pinterest-history',
		templates: '/app/ai-facebook-pages/templates',
		brandKit: '/app/ai-facebook-pages/brand-kit',
	},
	labels: {
		platformName: 'Chef IA',
		atelierTitle: 'AI Facebook Pages',
		itemSingular: 'Facebook Post',
		itemPlural: 'Facebook Posts',
		itemLower: 'post',
		itemLowerPlural: 'posts',
		productShort: 'Facebook Post',
		productShortPlural: 'Facebook Posts',
		account: 'Facebook account',
		accountTitle: 'Facebook Account',
		destination: 'Facebook Page',
		destinationLower: 'page',
		destinationPlural: 'pages',
		network: 'Facebook',
		connectCta: 'Connect Facebook',
		connectBannerTitle: 'Post created — connect Facebook next',
		connectBannerBody: 'Publishing requires a connected Facebook account and Facebook Page.',
		readyBanner: 'Facebook is ready — publish your first post to enter Operate Mode.',
		connectStudioHint: 'Connect Facebook to publish posts from this studio.',
		sizeSection: 'Post size',
		guidedSetup: (siteName) => `Create your first Facebook Post for ${siteName}, connect Facebook, then publish to finish setup.`,
		operateSubtitle: (siteName) => (siteName
			? `Compose Facebook-ready drafts for ${siteName} — then refine and publish.`
			: 'Compose Facebook-ready drafts from pages, bulk catalogs, or free prompts — then refine and publish.'),
		generateStep: 'Step 3 — Generate Posts',
		generateOne: 'Generate Post',
		generateMany: (n) => `Generate ${n} Posts`,
		emptyCanvas: 'Pick a mode on the left, tune quality and size, then generate. Previews appear here as tall Facebook cards with live progress.',
		libraryEmpty: 'Select articles above, choose a template, and generate Facebook Posts. When ready, publish to Facebook.',
		noDestination: 'No page',
		detailsTitle: 'Post details',
		targetDestination: 'Target Facebook Page',
		useGlobalDestination: 'Use global page',
		selectDestination: 'Select page',
		selectAccount: 'Select account',
		accountUnavailableTitle: 'Facebook account unavailable',
		accountUnavailableBody: 'Reconnect this Facebook account to load pages.',
		loadAccountsFailed: 'Failed to load Facebook accounts',
		loadDestinationsFailed: 'Failed to load Facebook Pages',
		chooseAccount: 'Choose a target Facebook account first.',
		chooseDestination: 'Choose a target Facebook Page.',
		accountNotFound: 'Facebook account not found. Connect Facebook first.',
		accountNotConnected: 'Facebook account is not connected. Reconnect it in Facebook settings.',
		analyzeDone: 'Facebook metadata was generated from the article.',
		missingLink: 'Cannot generate posts without a destination link for Facebook.',
		savedConnectNext: 'Next: connect Facebook so you can publish.',
		savedPublishSetup: 'draft(s) ready. Next: publish to finish setup.',
		savedPublishOperate: 'draft(s) ready. Next: publish or schedule from the library.',
		publishedItem: 'Post published',
		failedItem: 'Post failed',
		draftTitleFallback: 'Draft Facebook Post',
		scheduleTitle: (count) => `Schedule post${count > 1 ? 's' : ''}`,
		scheduleSubtitle: (count) => `${count} post${count === 1 ? '' : 's'} · appears on Calendar when scheduled`,
		previewTitle: 'Preview post',
		progressNetworkLabel: 'Facebook response',
		openOnNetwork: 'Open on Facebook',
		externalIdLabel: 'Post ID',
		historyNav: 'History',
		publishingHistoryNav: 'Publishing History',
		textOverlay: 'Post text overlay',
		numberOfItems: 'Number of posts',
		itemStyle: 'Post style',
		itemTitleSeed: 'Post title seed',
		targetAccount: 'Target account',
	},
	studioAssets: {
		defaultExportProfileId: 'facebook_post',
		exportProfileIds: ['facebook_post', 'facebook_story'],
		templatePackKey: 'facebook',
	},
};
