export const MOCK_AUDIT_LOGS = {
	summary: {
		totalToday: 1842,
		warnings: 46,
		errors: 18,
		critical: 3,
		security: 27,
		adminActions: 14,
	},
	events: [
		{
			id: 'evt_10021',
			timestamp: '2026-07-22 16:34:55',
			category: 'AI Requests',
			severity: 'Success',
			user: 'Maya Chen',
			workspace: 'Recipe Lab',
			service: 'AI Writer',
			action: 'Generate article draft',
			result: 'ok',
			ip: '185.22.10.44',
			duration: '1.18s',
			provider: 'OpenAI',
			model: 'gpt-4.1',
			credits: 12,
			correlationId: 'corr_9f2a11',
			request: { endpoint: '/ai/writer', method: 'POST' },
			response: { status: 200, words: 1840 },
			headers: { 'x-request-id': 'req_77a', 'user-agent': 'ChefIA/Web' },
			metadata: { plan: 'pro', locale: 'en' },
			timeline: [
				{ text: 'Request accepted', time: '16:34:54' },
				{ text: 'Provider responded', time: '16:34:55' },
			],
		},
		{
			id: 'evt_10022',
			timestamp: '2026-07-22 16:20:11',
			category: 'Queue Jobs',
			severity: 'Warning',
			user: 'system',
			workspace: '—',
			service: 'Job Queue',
			action: 'Queue depth elevated',
			result: 'degraded',
			ip: '10.0.0.12',
			duration: '—',
			provider: '—',
			model: '—',
			credits: 0,
			correlationId: 'corr_queue_62',
			request: {},
			response: { waiting: 23 },
			headers: {},
			metadata: { capacity: '62%' },
			timeline: [{ text: 'Alert opened', time: '16:20:11' }],
		},
		{
			id: 'evt_10023',
			timestamp: '2026-07-22 15:41:02',
			category: 'Authentication',
			severity: 'Error',
			user: 'unknown',
			workspace: '—',
			service: 'Auth',
			action: 'Failed login attempt',
			result: 'denied',
			ip: '91.204.55.18',
			duration: '120ms',
			provider: '—',
			model: '—',
			credits: 0,
			correlationId: 'corr_auth_882',
			request: { email: 'masked@example.com' },
			response: { status: 401 },
			headers: { 'x-forwarded-for': '91.204.55.18' },
			metadata: { reason: 'invalid_password' },
			timeline: [{ text: 'Credentials rejected', time: '15:41:02' }],
		},
		{
			id: 'evt_10024',
			timestamp: '2026-07-22 15:12:44',
			category: 'Image Generation',
			severity: 'Critical',
			user: 'Omar Vidal',
			workspace: 'Spice Route Media',
			service: 'Image Generator',
			action: 'Template render timeout',
			result: 'failed',
			ip: '78.11.22.9',
			duration: '30.1s',
			provider: 'Fal.ai',
			model: 'flux-dev',
			credits: 1,
			correlationId: 'corr_img_441',
			request: { templateId: 'tpl_44' },
			response: { status: 504, error: 'timeout' },
			headers: { 'x-fal-request': 'fal_991' },
			metadata: { retries: 1 },
			timeline: [
				{ text: 'Render started', time: '15:12:14' },
				{ text: 'Provider timeout', time: '15:12:44' },
			],
		},
		{
			id: 'evt_10025',
			timestamp: '2026-07-22 14:55:30',
			category: 'Security',
			severity: 'Warning',
			user: 'Amina Costa',
			workspace: 'Agency North',
			service: 'Admin Console',
			action: 'Role update',
			result: 'ok',
			ip: '102.33.8.71',
			duration: '80ms',
			provider: '—',
			model: '—',
			credits: 0,
			correlationId: 'corr_sec_19',
			request: { targetUser: 'u2', role: 'admin' },
			response: { status: 200 },
			headers: {},
			metadata: { actorRole: 'admin' },
			timeline: [{ text: 'Permission change recorded', time: '14:55:30' }],
		},
		{
			id: 'evt_10026',
			timestamp: '2026-07-22 14:24:35',
			category: 'Pinterest',
			severity: 'Success',
			user: 'Elena Duarte',
			workspace: 'Brunch Club',
			service: 'Publishing',
			action: 'Bulk pin publish',
			result: 'ok',
			ip: '45.66.12.3',
			duration: '4m 02s',
			provider: 'Pinterest',
			model: '—',
			credits: 24,
			correlationId: 'corr_pin_77',
			request: { pins: 36 },
			response: { published: 36 },
			headers: {},
			metadata: { board: 'Weekend Menu' },
			timeline: [{ text: 'Batch completed', time: '14:24:35' }],
		},
		{
			id: 'evt_10027',
			timestamp: '2026-07-22 13:58:10',
			category: 'WordPress',
			severity: 'Info',
			user: 'Sofia Reis',
			workspace: 'Pin Atelier',
			service: 'Publisher',
			action: 'Draft sync scheduled',
			result: 'queued',
			ip: '201.44.9.12',
			duration: '45ms',
			provider: 'WordPress',
			model: '—',
			credits: 0,
			correlationId: 'corr_wp_55',
			request: { site: 'pinatelier.blog' },
			response: { jobId: 'job_9904' },
			headers: {},
			metadata: {},
			timeline: [{ text: 'Awaiting token refresh', time: '13:58:10' }],
		},
		{
			id: 'evt_10028',
			timestamp: '2026-07-22 13:10:00',
			category: 'Subscriptions',
			severity: 'Success',
			user: 'Maya Chen',
			workspace: 'Recipe Lab',
			service: 'Billing',
			action: 'Plan upgraded to Pro',
			result: 'ok',
			ip: '185.22.10.44',
			duration: '640ms',
			provider: '—',
			model: '—',
			credits: 0,
			correlationId: 'corr_bill_3',
			request: { from: 'starter', to: 'pro' },
			response: { status: 200 },
			headers: {},
			metadata: { mrrDelta: 30 },
			timeline: [{ text: 'Subscription updated', time: '13:10:00' }],
		},
		{
			id: 'evt_10029',
			timestamp: '2026-07-22 12:40:22',
			category: 'Providers',
			severity: 'Info',
			user: 'Amina Costa',
			workspace: '—',
			service: 'Admin Console',
			action: 'Provider configuration opened',
			result: 'ok',
			ip: '102.33.8.71',
			duration: '20ms',
			provider: 'OpenAI',
			model: '—',
			credits: 0,
			correlationId: 'corr_adm_88',
			request: { providerId: 'openai' },
			response: { status: 200 },
			headers: {},
			metadata: { maskedSecrets: true },
			timeline: [{ text: 'Drawer opened', time: '12:40:22' }],
		},
		{
			id: 'evt_10030',
			timestamp: '2026-07-22 11:05:19',
			category: 'Workspaces',
			severity: 'Success',
			user: 'Jules Park',
			workspace: 'Recipes App',
			service: 'Onboarding',
			action: 'Workspace created',
			result: 'ok',
			ip: '66.12.90.4',
			duration: '210ms',
			provider: '—',
			model: '—',
			credits: 50,
			correlationId: 'corr_ws_12',
			request: { name: 'Recipes App' },
			response: { workspaceId: 'w8' },
			headers: {},
			metadata: { plan: 'starter' },
			timeline: [{ text: 'Workspace provisioned', time: '11:05:19' }],
		},
		{
			id: 'evt_10031',
			timestamp: '2026-07-22 10:22:00',
			category: 'API',
			severity: 'Warning',
			user: 'system',
			workspace: 'Agency North',
			service: 'API Gateway',
			action: 'Rate limit approaching',
			result: 'throttled',
			ip: '10.0.0.8',
			duration: '—',
			provider: 'Pinterest',
			model: '—',
			credits: 0,
			correlationId: 'corr_rate_9',
			request: {},
			response: { remaining: 120 },
			headers: {},
			metadata: { window: '1d' },
			timeline: [{ text: 'Quota warning emitted', time: '10:22:00' }],
		},
		{
			id: 'evt_10032',
			timestamp: '2026-07-22 09:44:03',
			category: 'System',
			severity: 'Success',
			user: 'system',
			workspace: 'Brunch Club',
			service: 'Webhooks',
			action: 'Webhook delivered',
			result: 'ok',
			ip: '10.0.0.21',
			duration: '1.2s',
			provider: '—',
			model: '—',
			credits: 0,
			correlationId: 'corr_hook_2',
			request: { event: 'publish.completed' },
			response: { statusCode: 200 },
			headers: {},
			metadata: {},
			timeline: [{ text: 'Customer endpoint 200', time: '09:44:03' }],
		},
	],
	securityEvents: [
		{ id: 'sec1', title: 'Failed Login', detail: '91.204.55.18 · invalid password', time: '15:41' },
		{ id: 'sec2', title: 'Permission Changes', detail: 'Amina Costa updated role for Leo Martins', time: '14:55' },
		{ id: 'sec3', title: 'API Key Changes', detail: 'OpenAI key mask rotated (UI only)', time: 'Yesterday' },
		{ id: 'sec4', title: 'Role Updates', detail: 'Admin role grant pending review', time: 'Yesterday' },
		{ id: 'sec5', title: 'Suspicious Activity', detail: '5 failed logins from same ASN', time: '2d ago' },
		{ id: 'sec6', title: 'Rate Limits', detail: 'Pinterest daily quota 88% used', time: '10:22' },
	],
	adminActivity: [
		{ id: 'adm1', text: 'Admin login · Amina Costa', time: '16:01' },
		{ id: 'adm2', text: 'Plan edited · Pro credits preview', time: '15:20' },
		{ id: 'adm3', text: 'Provider configured · Fal.ai drawer opened', time: '12:40' },
		{ id: 'adm4', text: 'Model changed · flux-pro set default (UI)', time: '11:55' },
		{ id: 'adm5', text: 'User suspended · Noah Silva', time: 'Jul 20' },
		{ id: 'adm6', text: 'Workspace deleted · preview only', time: 'Jul 18' },
	],
	systemLogs: [
		'[16:35:02] health.check overall=healthy',
		'[16:34:59] queue.depth=23',
		'[16:20:11] alert.opened service=Job Queue',
		'[15:41:02] auth.failed ip=91.204.55.18',
		'[15:12:44] fal.timeout template=tpl_44',
		'[14:55:30] rbac.role_update actor=amina',
		'[13:10:00] billing.upgrade workspace=Recipe Lab',
		'[11:05:19] workspace.created Recipes App',
	],
};
