export const MOCK_STATS = {
	activeUsers: 1284,
	workspaces: 912,
	creditsUsed: 48290,
	aiRequests: 19340,
	revenue: 18420,
	serverHealth: 'Operational',
};

export const MOCK_USERS = [
	{
		id: 'u1',
		name: 'Amina Costa',
		email: 'amina@example.com',
		role: 'admin',
		status: 'active',
		plan: 'agency',
		credits: 22000,
		workspaces: ['Agency North', 'Chef IA Ops'],
		created: '2026-01-12',
		lastLogin: '2026-07-22 09:14',
		subscription: { plan: 'agency', renews: '2026-08-12', seats: 12 },
		websites: [{ domain: 'agencynorth.com', status: 'connected' }, { domain: 'ops.chef-ia.example', status: 'connected' }],
		pinterest: 'connected',
		wordpress: 'connected',
		activity: [
			{ text: 'Opened Admin Console', time: '2h ago' },
			{ text: 'Granted credits to Recipe Lab', time: '1d ago' },
		],
	},
	{
		id: 'u2',
		name: 'Leo Martins',
		email: 'leo@foodblog.io',
		role: 'user',
		status: 'active',
		plan: 'pro',
		credits: 4200,
		workspaces: ['Sunday Kitchen'],
		created: '2026-02-03',
		lastLogin: '2026-07-21 18:40',
		subscription: { plan: 'pro', renews: '2026-08-03', seats: 1 },
		websites: [{ domain: 'sundaykitchen.com', status: 'connected' }],
		pinterest: 'connected',
		wordpress: 'connected',
		activity: [
			{ text: 'Published 4 pins', time: '5h ago' },
			{ text: 'Generated AI Writer draft', time: '1d ago' },
		],
	},
	{
		id: 'u3',
		name: 'Sofia Reis',
		email: 'sofia@pins.co',
		role: 'user',
		status: 'invited',
		plan: 'starter',
		credits: 890,
		workspaces: ['Pin Atelier'],
		created: '2026-03-18',
		lastLogin: '—',
		subscription: { plan: 'starter', renews: '2026-08-18', seats: 1 },
		websites: [{ domain: 'pinatelier.blog', status: 'pending' }],
		pinterest: 'pending',
		wordpress: 'pending',
		activity: [
			{ text: 'Invite accepted pending verification', time: '3d ago' },
		],
	},
	{
		id: 'u4',
		name: 'Noah Silva',
		email: 'noah@kitchen.dev',
		role: 'user',
		status: 'suspended',
		plan: 'free',
		credits: 0,
		workspaces: ['Kitchen Dev'],
		created: '2026-04-01',
		lastLogin: '2026-06-11 11:02',
		subscription: { plan: 'free', renews: '—', seats: 1 },
		websites: [],
		pinterest: 'disconnected',
		wordpress: 'disconnected',
		activity: [
			{ text: 'Account suspended for billing review', time: '12d ago' },
		],
	},
	{
		id: 'u5',
		name: 'Maya Chen',
		email: 'maya@atelier.ai',
		role: 'user',
		status: 'active',
		plan: 'pro',
		credits: 3100,
		workspaces: ['Recipe Lab'],
		created: '2026-05-22',
		lastLogin: '2026-07-22 08:02',
		subscription: { plan: 'pro', renews: '2026-08-22', seats: 2 },
		websites: [{ domain: 'recipelab.io', status: 'degraded' }],
		pinterest: 'connected',
		wordpress: 'degraded',
		activity: [
			{ text: 'Upgraded to Pro', time: '12m ago' },
			{ text: 'Connected Brand Kit', time: '2d ago' },
		],
	},
	{
		id: 'u6',
		name: 'Jules Park',
		email: 'jules@recipes.app',
		role: 'user',
		status: 'active',
		plan: 'starter',
		credits: 640,
		workspaces: ['Recipes App'],
		created: '2026-06-09',
		lastLogin: '2026-07-20 16:27',
		subscription: { plan: 'starter', renews: '2026-08-09', seats: 1 },
		websites: [{ domain: 'recipes.app', status: 'connected' }],
		pinterest: 'connected',
		wordpress: 'connected',
		activity: [
			{ text: 'Completed onboarding step 3', time: '1d ago' },
		],
	},
	{
		id: 'u7',
		name: 'Elena Duarte',
		email: 'elena@brunch.club',
		role: 'user',
		status: 'active',
		plan: 'pro',
		credits: 1850,
		workspaces: ['Brunch Club', 'Weekend Menu'],
		created: '2026-07-01',
		lastLogin: '2026-07-22 07:45',
		subscription: { plan: 'pro', renews: '2026-08-01', seats: 3 },
		websites: [
			{ domain: 'brunch.club', status: 'connected' },
			{ domain: 'weekendmenu.co', status: 'connected' },
		],
		pinterest: 'connected',
		wordpress: 'connected',
		activity: [
			{ text: 'Scheduled calendar batch', time: '4h ago' },
		],
	},
	{
		id: 'u8',
		name: 'Omar Vidal',
		email: 'omar@spice.route',
		role: 'admin',
		status: 'active',
		plan: 'agency',
		credits: 9800,
		workspaces: ['Spice Route Media'],
		created: '2026-07-08',
		lastLogin: '2026-07-21 22:10',
		subscription: { plan: 'agency', renews: '2026-08-08', seats: 8 },
		websites: [{ domain: 'spiceroute.media', status: 'connected' }],
		pinterest: 'connected',
		wordpress: 'connected',
		activity: [
			{ text: 'Reviewed queue failures', time: '6h ago' },
		],
	},
];

export const MOCK_WORKSPACES = [
	{
		id: 'w1',
		name: 'Sunday Kitchen',
		owner: 'Leo Martins',
		ownerEmail: 'leo@foodblog.io',
		plan: 'pro',
		credits: 4200,
		creditsUsed: 1800,
		status: 'active',
		created: '2026-02-03',
		lastActivity: '2026-07-21 18:40',
		websites: [{ domain: 'sundaykitchen.com', status: 'connected' }],
		pinterestConnected: true,
		wordpressConnected: true,
		pinterestAccounts: [{ name: 'Sunday Kitchen Pins', boards: 12, status: 'connected' }],
		wordpressConnections: [{ site: 'sundaykitchen.com', status: 'connected' }],
		publishing: [
			{ text: 'Published 4 pins to Board Recipes', time: '5h ago' },
			{ text: 'WordPress draft synced', time: '1d ago' },
		],
		storageUsedGb: 2.4,
		storageLimitGb: 20,
		subscription: { plan: 'pro', renews: '2026-08-03', seats: 1 },
	},
	{
		id: 'w2',
		name: 'Pin Atelier',
		owner: 'Sofia Reis',
		ownerEmail: 'sofia@pins.co',
		plan: 'starter',
		credits: 890,
		creditsUsed: 110,
		status: 'trial',
		created: '2026-03-18',
		lastActivity: '2026-07-10 09:12',
		websites: [{ domain: 'pinatelier.blog', status: 'pending' }],
		pinterestConnected: false,
		wordpressConnected: false,
		pinterestAccounts: [],
		wordpressConnections: [],
		publishing: [
			{ text: 'Workspace invite pending verification', time: '3d ago' },
		],
		storageUsedGb: 0.3,
		storageLimitGb: 5,
		subscription: { plan: 'starter', renews: '2026-08-18', seats: 1 },
	},
	{
		id: 'w3',
		name: 'Agency North',
		owner: 'Amina Costa',
		ownerEmail: 'amina@example.com',
		plan: 'agency',
		credits: 22000,
		creditsUsed: 8400,
		status: 'active',
		created: '2026-01-12',
		lastActivity: '2026-07-22 09:14',
		websites: [
			{ domain: 'agencynorth.com', status: 'connected' },
			{ domain: 'ops.chef-ia.example', status: 'connected' },
		],
		pinterestConnected: true,
		wordpressConnected: true,
		pinterestAccounts: [
			{ name: 'Agency Multi', boards: 28, status: 'connected' },
			{ name: 'Client Pack A', boards: 9, status: 'connected' },
		],
		wordpressConnections: [
			{ site: 'agencynorth.com', status: 'connected' },
			{ site: 'ops.chef-ia.example', status: 'connected' },
		],
		publishing: [
			{ text: 'Batch publish completed (18 pins)', time: '2h ago' },
			{ text: 'Credits grant applied', time: '1d ago' },
		],
		storageUsedGb: 11.2,
		storageLimitGb: 100,
		subscription: { plan: 'agency', renews: '2026-08-12', seats: 12 },
	},
	{
		id: 'w4',
		name: 'Recipe Lab',
		owner: 'Maya Chen',
		ownerEmail: 'maya@atelier.ai',
		plan: 'pro',
		credits: 3100,
		creditsUsed: 920,
		status: 'active',
		created: '2026-05-22',
		lastActivity: '2026-07-22 08:02',
		websites: [{ domain: 'recipelab.io', status: 'degraded' }],
		pinterestConnected: true,
		wordpressConnected: true,
		pinterestAccounts: [{ name: 'Recipe Lab Pins', boards: 7, status: 'connected' }],
		wordpressConnections: [{ site: 'recipelab.io', status: 'degraded' }],
		publishing: [
			{ text: 'Upgraded to Pro', time: '12m ago' },
			{ text: 'Brand Kit connected', time: '2d ago' },
		],
		storageUsedGb: 4.1,
		storageLimitGb: 20,
		subscription: { plan: 'pro', renews: '2026-08-22', seats: 2 },
	},
	{
		id: 'w5',
		name: 'Kitchen Dev',
		owner: 'Noah Silva',
		ownerEmail: 'noah@kitchen.dev',
		plan: 'free',
		credits: 0,
		creditsUsed: 120,
		status: 'suspended',
		created: '2026-04-01',
		lastActivity: '2026-06-11 11:02',
		websites: [],
		pinterestConnected: false,
		wordpressConnected: false,
		pinterestAccounts: [],
		wordpressConnections: [],
		publishing: [
			{ text: 'Workspace suspended for billing review', time: '12d ago' },
		],
		storageUsedGb: 0.1,
		storageLimitGb: 2,
		subscription: { plan: 'free', renews: '—', seats: 1 },
	},
	{
		id: 'w6',
		name: 'Brunch Club',
		owner: 'Elena Duarte',
		ownerEmail: 'elena@brunch.club',
		plan: 'pro',
		credits: 1850,
		creditsUsed: 640,
		status: 'active',
		created: '2026-07-01',
		lastActivity: '2026-07-22 07:45',
		websites: [
			{ domain: 'brunch.club', status: 'connected' },
			{ domain: 'weekendmenu.co', status: 'connected' },
		],
		pinterestConnected: true,
		wordpressConnected: true,
		pinterestAccounts: [{ name: 'Brunch Club', boards: 15, status: 'connected' }],
		wordpressConnections: [
			{ site: 'brunch.club', status: 'connected' },
			{ site: 'weekendmenu.co', status: 'connected' },
		],
		publishing: [
			{ text: 'Scheduled calendar batch', time: '4h ago' },
		],
		storageUsedGb: 3.6,
		storageLimitGb: 20,
		subscription: { plan: 'pro', renews: '2026-08-01', seats: 3 },
	},
	{
		id: 'w7',
		name: 'Spice Route Media',
		owner: 'Omar Vidal',
		ownerEmail: 'omar@spice.route',
		plan: 'agency',
		credits: 9800,
		creditsUsed: 2100,
		status: 'active',
		created: '2026-07-08',
		lastActivity: '2026-07-21 22:10',
		websites: [{ domain: 'spiceroute.media', status: 'connected' }],
		pinterestConnected: true,
		wordpressConnected: true,
		pinterestAccounts: [{ name: 'Spice Route', boards: 21, status: 'connected' }],
		wordpressConnections: [{ site: 'spiceroute.media', status: 'connected' }],
		publishing: [
			{ text: 'Reviewed queue failures', time: '6h ago' },
		],
		storageUsedGb: 6.8,
		storageLimitGb: 100,
		subscription: { plan: 'agency', renews: '2026-08-08', seats: 8 },
	},
	{
		id: 'w8',
		name: 'Recipes App',
		owner: 'Jules Park',
		ownerEmail: 'jules@recipes.app',
		plan: 'starter',
		credits: 640,
		creditsUsed: 80,
		status: 'active',
		created: '2026-06-09',
		lastActivity: '2026-07-20 16:27',
		websites: [{ domain: 'recipes.app', status: 'connected' }],
		pinterestConnected: true,
		wordpressConnected: true,
		pinterestAccounts: [{ name: 'Recipes App Pins', boards: 4, status: 'connected' }],
		wordpressConnections: [{ site: 'recipes.app', status: 'connected' }],
		publishing: [
			{ text: 'Completed onboarding step 3', time: '1d ago' },
		],
		storageUsedGb: 0.9,
		storageLimitGb: 5,
		subscription: { plan: 'starter', renews: '2026-08-09', seats: 1 },
	},
];

export const MOCK_PROVIDERS = [
	{ id: 'openai', name: 'OpenAI', status: 'connected', models: 12, latency: '420ms' },
	{ id: 'gemini', name: 'Gemini', status: 'connected', models: 6, latency: '510ms' },
	{ id: 'claude', name: 'Claude', status: 'ready', models: 5, latency: '—' },
	{ id: 'openrouter', name: 'OpenRouter', status: 'ready', models: 40, latency: '—' },
	{ id: 'deepseek', name: 'DeepSeek', status: 'ready', models: 4, latency: '—' },
	{ id: 'grok', name: 'Grok', status: 'ready', models: 3, latency: '—' },
	{ id: 'mistral', name: 'Mistral', status: 'ready', models: 7, latency: '—' },
	{ id: 'replicate', name: 'Replicate', status: 'ready', models: 18, latency: '—' },
	{ id: 'fal', name: 'Fal.ai', status: 'connected', models: 22, latency: '380ms' },
];

export const MOCK_MODELS = [
	{ id: 'm1', provider: 'OpenAI', name: 'gpt-4.1', type: 'text', status: 'enabled' },
	{ id: 'm2', provider: 'OpenAI', name: 'gpt-image-1', type: 'image', status: 'enabled' },
	{ id: 'm3', provider: 'Gemini', name: 'gemini-2.5-pro', type: 'text', status: 'enabled' },
	{ id: 'm4', provider: 'Fal.ai', name: 'flux-pro', type: 'image', status: 'enabled' },
	{ id: 'm5', provider: 'Claude', name: 'claude-sonnet-4', type: 'text', status: 'disabled' },
];

export const MOCK_LOGS = [
	{ id: 'l1', severity: 'info', message: 'Credits ledger synced', source: 'billing', at: '2026-07-22 14:02:11' },
	{ id: 'l2', severity: 'warn', message: 'Pinterest rate limit approaching', source: 'pinterest', at: '2026-07-22 13:48:02' },
	{ id: 'l3', severity: 'error', message: 'Image worker timeout on job #8821', source: 'workers', at: '2026-07-22 13:12:44' },
	{ id: 'l4', severity: 'info', message: 'New workspace created: Recipe Lab', source: 'auth', at: '2026-07-22 12:05:19' },
	{ id: 'l5', severity: 'debug', message: 'Queue drain cycle completed', source: 'queue', at: '2026-07-22 11:59:01' },
];

export const MOCK_QUEUE = {
	running: 7,
	waiting: 23,
	completed: 1482,
	failed: 12,
	retry: 4,
	jobs: [
		{ id: 'j1', name: 'Generate pin pack', status: 'running', workspace: 'Sunday Kitchen', age: '42s' },
		{ id: 'j2', name: 'Publish WordPress draft', status: 'waiting', workspace: 'Pin Atelier', age: '2m' },
		{ id: 'j3', name: 'Optimize prompts', status: 'completed', workspace: 'Agency North', age: '8m' },
		{ id: 'j4', name: 'Fal image render', status: 'failed', workspace: 'Recipe Lab', age: '14m' },
		{ id: 'j5', name: 'Credit top-up webhook', status: 'retry', workspace: 'Agency North', age: '3m' },
	],
};

export const MOCK_HEALTH = [
	{ name: 'API Status', status: 'healthy', detail: '99.98% uptime' },
	{ name: 'Database', status: 'healthy', detail: 'PocketBase primary' },
	{ name: 'Queue', status: 'degraded', detail: '23 waiting jobs' },
	{ name: 'Storage', status: 'healthy', detail: '68% capacity' },
	{ name: 'Workers', status: 'healthy', detail: '4 / 4 online' },
	{ name: 'Email', status: 'healthy', detail: 'SMTP ready' },
	{ name: 'AI Providers', status: 'healthy', detail: '3 connected' },
];

export const MOCK_ACTIVITY = [
	{ id: 'a1', text: 'Maya Chen upgraded to Pro', time: '12m ago' },
	{ id: 'a2', text: 'Fal.ai provider health check passed', time: '28m ago' },
	{ id: 'a3', text: 'Queue retry scheduled for job #8821', time: '41m ago' },
	{ id: 'a4', text: 'New registration: Jules Park', time: '1h ago' },
];

export const MOCK_ALERTS = [
	{ id: 'al1', tone: 'amber', text: 'Pinterest API approaching daily quota' },
	{ id: 'al2', tone: 'red', text: '12 failed image jobs in the last hour' },
	{ id: 'al3', tone: 'green', text: 'Maintenance window cleared' },
];
