export const MOCK_STATS = {
	activeUsers: 1284,
	workspaces: 912,
	creditsUsed: 48290,
	aiRequests: 19340,
	revenue: 18420,
	serverHealth: 'Operational',
};

export const MOCK_USERS = [
	{
		id: 'u1',
		name: 'Amina Costa',
		email: 'amina@example.com',
		role: 'admin',
		status: 'active',
		plan: 'agency',
		credits: 22000,
		workspaces: ['Agency North', 'Chef IA Ops'],
		created: '2026-01-12',
		lastLogin: '2026-07-22 09:14',
		subscription: { plan: 'agency', renews: '2026-08-12', seats: 12 },
		websites: [{ domain: 'agencynorth.com', status: 'connected' }, { domain: 'ops.chef-ia.example', status: 'connected' }],
		pinterest: 'connected',
		wordpress: 'connected',
		activity: [
			{ text: 'Opened Admin Console', time: '2h ago' },
			{ text: 'Granted credits to Recipe Lab', time: '1d ago' },
		],
	},
	{
		id: 'u2',
		name: 'Leo Martins',
		email: 'leo@foodblog.io',
		role: 'user',
		status: 'active',
		plan: 'pro',
		credits: 4200,
		workspaces: ['Sunday Kitchen'],
		created: '2026-02-03',
		lastLogin: '2026-07-21 18:40',
		subscription: { plan: 'pro', renews: '2026-08-03', seats: 1 },
		websites: [{ domain: 'sundaykitchen.com', status: 'connected' }],
		pinterest: 'connected',
		wordpress: 'connected',
		activity: [
			{ text: 'Published 4 pins', time: '5h ago' },
			{ text: 'Generated AI Writer draft', time: '1d ago' },
		],
	},
	{
		id: 'u3',
		name: 'Sofia Reis',
		email: 'sofia@pins.co',
		role: 'user',
		status: 'invited',
		plan: 'starter',
		credits: 890,
		workspaces: ['Pin Atelier'],
		created: '2026-03-18',
		lastLogin: '—',
		subscription: { plan: 'starter', renews: '2026-08-18', seats: 1 },
		websites: [{ domain: 'pinatelier.blog', status: 'pending' }],
		pinterest: 'pending',
		wordpress: 'pending',
		activity: [
			{ text: 'Invite accepted pending verification', time: '3d ago' },
		],
	},
	{
		id: 'u4',
		name: 'Noah Silva',
		email: 'noah@kitchen.dev',
		role: 'user',
		status: 'suspended',
		plan: 'free',
		credits: 0,
		workspaces: ['Kitchen Dev'],
		created: '2026-04-01',
		lastLogin: '2026-06-11 11:02',
		subscription: { plan: 'free', renews: '—', seats: 1 },
		websites: [],
		pinterest: 'disconnected',
		wordpress: 'disconnected',
		activity: [
			{ text: 'Account suspended for billing review', time: '12d ago' },
		],
	},
	{
		id: 'u5',
		name: 'Maya Chen',
		email: 'maya@atelier.ai',
		role: 'user',
		status: 'active',
		plan: 'pro',
		credits: 3100,
		workspaces: ['Recipe Lab'],
		created: '2026-05-22',
		lastLogin: '2026-07-22 08:02',
		subscription: { plan: 'pro', renews: '2026-08-22', seats: 2 },
		websites: [{ domain: 'recipelab.io', status: 'degraded' }],
		pinterest: 'connected',
		wordpress: 'degraded',
		activity: [
			{ text: 'Upgraded to Pro', time: '12m ago' },
			{ text: 'Connected Brand Kit', time: '2d ago' },
		],
	},
	{
		id: 'u6',
		name: 'Jules Park',
		email: 'jules@recipes.app',
		role: 'user',
		status: 'active',
		plan: 'starter',
		credits: 640,
		workspaces: ['Recipes App'],
		created: '2026-06-09',
		lastLogin: '2026-07-20 16:27',
		subscription: { plan: 'starter', renews: '2026-08-09', seats: 1 },
		websites: [{ domain: 'recipes.app', status: 'connected' }],
		pinterest: 'connected',
		wordpress: 'connected',
		activity: [
			{ text: 'Completed onboarding step 3', time: '1d ago' },
		],
	},
	{
		id: 'u7',
		name: 'Elena Duarte',
		email: 'elena@brunch.club',
		role: 'user',
		status: 'active',
		plan: 'pro',
		credits: 1850,
		workspaces: ['Brunch Club', 'Weekend Menu'],
		created: '2026-07-01',
		lastLogin: '2026-07-22 07:45',
		subscription: { plan: 'pro', renews: '2026-08-01', seats: 3 },
		websites: [
			{ domain: 'brunch.club', status: 'connected' },
			{ domain: 'weekendmenu.co', status: 'connected' },
		],
		pinterest: 'connected',
		wordpress: 'connected',
		activity: [
			{ text: 'Scheduled calendar batch', time: '4h ago' },
		],
	},
	{
		id: 'u8',
		name: 'Omar Vidal',
		email: 'omar@spice.route',
		role: 'admin',
		status: 'active',
		plan: 'agency',
		credits: 9800,
		workspaces: ['Spice Route Media'],
		created: '2026-07-08',
		lastLogin: '2026-07-21 22:10',
		subscription: { plan: 'agency', renews: '2026-08-08', seats: 8 },
		websites: [{ domain: 'spiceroute.media', status: 'connected' }],
		pinterest: 'connected',
		wordpress: 'connected',
		activity: [
			{ text: 'Reviewed queue failures', time: '6h ago' },
		],
	},
];

export const MOCK_WORKSPACES = [
	{
		id: 'w1',
		name: 'Sunday Kitchen',
		owner: 'Leo Martins',
		ownerEmail: 'leo@foodblog.io',
		plan: 'pro',
		credits: 4200,
		creditsUsed: 1800,
		status: 'active',
		created: '2026-02-03',
		lastActivity: '2026-07-21 18:40',
		websites: [{ domain: 'sundaykitchen.com', status: 'connected' }],
		pinterestConnected: true,
		wordpressConnected: true,
		pinterestAccounts: [{ name: 'Sunday Kitchen Pins', boards: 12, status: 'connected' }],
		wordpressConnections: [{ site: 'sundaykitchen.com', status: 'connected' }],
		publishing: [
			{ text: 'Published 4 pins to Board Recipes', time: '5h ago' },
			{ text: 'WordPress draft synced', time: '1d ago' },
		],
		storageUsedGb: 2.4,
		storageLimitGb: 20,
		subscription: { plan: 'pro', renews: '2026-08-03', seats: 1 },
	},
	{
		id: 'w2',
		name: 'Pin Atelier',
		owner: 'Sofia Reis',
		ownerEmail: 'sofia@pins.co',
		plan: 'starter',
		credits: 890,
		creditsUsed: 110,
		status: 'trial',
		created: '2026-03-18',
		lastActivity: '2026-07-10 09:12',
		websites: [{ domain: 'pinatelier.blog', status: 'pending' }],
		pinterestConnected: false,
		wordpressConnected: false,
		pinterestAccounts: [],
		wordpressConnections: [],
		publishing: [
			{ text: 'Workspace invite pending verification', time: '3d ago' },
		],
		storageUsedGb: 0.3,
		storageLimitGb: 5,
		subscription: { plan: 'starter', renews: '2026-08-18', seats: 1 },
	},
	{
		id: 'w3',
		name: 'Agency North',
		owner: 'Amina Costa',
		ownerEmail: 'amina@example.com',
		plan: 'agency',
		credits: 22000,
		creditsUsed: 8400,
		status: 'active',
		created: '2026-01-12',
		lastActivity: '2026-07-22 09:14',
		websites: [
			{ domain: 'agencynorth.com', status: 'connected' },
			{ domain: 'ops.chef-ia.example', status: 'connected' },
		],
		pinterestConnected: true,
		wordpressConnected: true,
		pinterestAccounts: [
			{ name: 'Agency Multi', boards: 28, status: 'connected' },
			{ name: 'Client Pack A', boards: 9, status: 'connected' },
		],
		wordpressConnections: [
			{ site: 'agencynorth.com', status: 'connected' },
			{ site: 'ops.chef-ia.example', status: 'connected' },
		],
		publishing: [
			{ text: 'Batch publish completed (18 pins)', time: '2h ago' },
			{ text: 'Credits grant applied', time: '1d ago' },
		],
		storageUsedGb: 11.2,
		storageLimitGb: 100,
		subscription: { plan: 'agency', renews: '2026-08-12', seats: 12 },
	},
	{
		id: 'w4',
		name: 'Recipe Lab',
		owner: 'Maya Chen',
		ownerEmail: 'maya@atelier.ai',
		plan: 'pro',
		credits: 3100,
		creditsUsed: 920,
		status: 'active',
		created: '2026-05-22',
		lastActivity: '2026-07-22 08:02',
		websites: [{ domain: 'recipelab.io', status: 'degraded' }],
		pinterestConnected: true,
		wordpressConnected: true,
		pinterestAccounts: [{ name: 'Recipe Lab Pins', boards: 7, status: 'connected' }],
		wordpressConnections: [{ site: 'recipelab.io', status: 'degraded' }],
		publishing: [
			{ text: 'Upgraded to Pro', time: '12m ago' },
			{ text: 'Brand Kit connected', time: '2d ago' },
		],
		storageUsedGb: 4.1,
		storageLimitGb: 20,
		subscription: { plan: 'pro', renews: '2026-08-22', seats: 2 },
	},
	{
		id: 'w5',
		name: 'Kitchen Dev',
		owner: 'Noah Silva',
		ownerEmail: 'noah@kitchen.dev',
		plan: 'free',
		credits: 0,
		creditsUsed: 120,
		status: 'suspended',
		created: '2026-04-01',
		lastActivity: '2026-06-11 11:02',
		websites: [],
		pinterestConnected: false,
		wordpressConnected: false,
		pinterestAccounts: [],
		wordpressConnections: [],
		publishing: [
			{ text: 'Workspace suspended for billing review', time: '12d ago' },
		],
		storageUsedGb: 0.1,
		storageLimitGb: 2,
		subscription: { plan: 'free', renews: '—', seats: 1 },
	},
	{
		id: 'w6',
		name: 'Brunch Club',
		owner: 'Elena Duarte',
		ownerEmail: 'elena@brunch.club',
		plan: 'pro',
		credits: 1850,
		creditsUsed: 640,
		status: 'active',
		created: '2026-07-01',
		lastActivity: '2026-07-22 07:45',
		websites: [
			{ domain: 'brunch.club', status: 'connected' },
			{ domain: 'weekendmenu.co', status: 'connected' },
		],
		pinterestConnected: true,
		wordpressConnected: true,
		pinterestAccounts: [{ name: 'Brunch Club', boards: 15, status: 'connected' }],
		wordpressConnections: [
			{ site: 'brunch.club', status: 'connected' },
			{ site: 'weekendmenu.co', status: 'connected' },
		],
		publishing: [
			{ text: 'Scheduled calendar batch', time: '4h ago' },
		],
		storageUsedGb: 3.6,
		storageLimitGb: 20,
		subscription: { plan: 'pro', renews: '2026-08-01', seats: 3 },
	},
	{
		id: 'w7',
		name: 'Spice Route Media',
		owner: 'Omar Vidal',
		ownerEmail: 'omar@spice.route',
		plan: 'agency',
		credits: 9800,
		creditsUsed: 2100,
		status: 'active',
		created: '2026-07-08',
		lastActivity: '2026-07-21 22:10',
		websites: [{ domain: 'spiceroute.media', status: 'connected' }],
		pinterestConnected: true,
		wordpressConnected: true,
		pinterestAccounts: [{ name: 'Spice Route', boards: 21, status: 'connected' }],
		wordpressConnections: [{ site: 'spiceroute.media', status: 'connected' }],
		publishing: [
			{ text: 'Reviewed queue failures', time: '6h ago' },
		],
		storageUsedGb: 6.8,
		storageLimitGb: 100,
		subscription: { plan: 'agency', renews: '2026-08-08', seats: 8 },
	},
	{
		id: 'w8',
		name: 'Recipes App',
		owner: 'Jules Park',
		ownerEmail: 'jules@recipes.app',
		plan: 'starter',
		credits: 640,
		creditsUsed: 80,
		status: 'active',
		created: '2026-06-09',
		lastActivity: '2026-07-20 16:27',
		websites: [{ domain: 'recipes.app', status: 'connected' }],
		pinterestConnected: true,
		wordpressConnected: true,
		pinterestAccounts: [{ name: 'Recipes App Pins', boards: 4, status: 'connected' }],
		wordpressConnections: [{ site: 'recipes.app', status: 'connected' }],
		publishing: [
			{ text: 'Completed onboarding step 3', time: '1d ago' },
		],
		storageUsedGb: 0.9,
		storageLimitGb: 5,
		subscription: { plan: 'starter', renews: '2026-08-09', seats: 1 },
	},
];

export const MOCK_PROVIDERS = [
	{
		id: 'openai',
		name: 'OpenAI',
		badge: 'OA',
		accent: 'from-[#10a37f] to-[#0d8f6e]',
		status: 'connected',
		enabled: true,
		health: 'healthy',
		lastChecked: '2026-07-22 14:02',
		currentModel: 'gpt-4.1',
		endpoint: 'https://api.openai.com/v1',
		apiVersion: 'v1',
		rateLimit: '10,000 RPM',
		lastSuccess: '2026-07-22 13:58',
		lastError: '—',
		models: ['gpt-4.1', 'gpt-4.1-mini', 'gpt-image-1'],
		history: [
			{ text: 'Default model set to gpt-4.1', time: '2d ago' },
			{ text: 'API key rotated (masked)', time: '12d ago' },
		],
		config: {
			apiKey: 'sk-••••••••••••••••',
			secretKey: '',
			organizationId: 'org_••••',
			baseUrl: 'https://api.openai.com/v1',
			webhookUrl: '',
			redirectUri: '',
			scopes: 'chat,images',
			timeout: '30s',
			retryPolicy: '3 exponential',
			defaultModel: 'gpt-4.1',
		},
	},
	{
		id: 'gemini',
		name: 'Google Gemini',
		badge: 'G',
		accent: 'from-[#4285F4] to-[#34A853]',
		status: 'connected',
		enabled: true,
		health: 'healthy',
		lastChecked: '2026-07-22 13:50',
		currentModel: 'gemini-2.5-pro',
		endpoint: 'https://generativelanguage.googleapis.com',
		apiVersion: 'v1beta',
		rateLimit: '1,000 RPM',
		lastSuccess: '2026-07-22 13:49',
		lastError: '—',
		models: ['gemini-2.5-pro', 'gemini-2.5-flash'],
		history: [{ text: 'Health check passed', time: '1h ago' }],
		config: {
			apiKey: 'AIza••••••••',
			secretKey: '',
			organizationId: '',
			baseUrl: 'https://generativelanguage.googleapis.com',
			webhookUrl: '',
			redirectUri: '',
			scopes: 'generateContent',
			timeout: '45s',
			retryPolicy: '2 linear',
			defaultModel: 'gemini-2.5-pro',
		},
	},
	{
		id: 'claude',
		name: 'Anthropic Claude',
		badge: 'C',
		accent: 'from-[#d97757] to-[#b45309]',
		status: 'disconnected',
		enabled: false,
		health: 'unknown',
		lastChecked: '2026-07-20 09:11',
		currentModel: 'claude-sonnet-4',
		endpoint: 'https://api.anthropic.com',
		apiVersion: '2023-06-01',
		rateLimit: '—',
		lastSuccess: '—',
		lastError: 'Missing API key',
		models: ['claude-sonnet-4', 'claude-opus-4'],
		history: [{ text: 'Provider disabled by admin', time: '5d ago' }],
		config: {
			apiKey: '',
			secretKey: '',
			organizationId: '',
			baseUrl: 'https://api.anthropic.com',
			webhookUrl: '',
			redirectUri: '',
			scopes: 'messages',
			timeout: '60s',
			retryPolicy: '3 exponential',
			defaultModel: 'claude-sonnet-4',
		},
	},
	{
		id: 'openrouter',
		name: 'OpenRouter',
		badge: 'OR',
		accent: 'from-[#8b5cf6] to-[#6366f1]',
		status: 'disconnected',
		enabled: false,
		health: 'unknown',
		lastChecked: '2026-07-18 16:22',
		currentModel: 'auto',
		endpoint: 'https://openrouter.ai/api/v1',
		apiVersion: 'v1',
		rateLimit: '—',
		lastSuccess: '—',
		lastError: 'Not configured',
		models: ['openai/gpt-4.1', 'anthropic/claude-sonnet-4', 'google/gemini-2.5-pro'],
		history: [{ text: 'Card created — awaiting key', time: '20d ago' }],
		config: {
			apiKey: '',
			secretKey: '',
			organizationId: '',
			baseUrl: 'https://openrouter.ai/api/v1',
			webhookUrl: '',
			redirectUri: '',
			scopes: 'chat',
			timeout: '45s',
			retryPolicy: '2 exponential',
			defaultModel: 'auto',
		},
	},
	{
		id: 'deepseek',
		name: 'DeepSeek',
		badge: 'DS',
		accent: 'from-[#4f46e5] to-[#0ea5e9]',
		status: 'disconnected',
		enabled: false,
		health: 'unknown',
		lastChecked: '2026-07-15 11:03',
		currentModel: 'deepseek-chat',
		endpoint: 'https://api.deepseek.com',
		apiVersion: 'v1',
		rateLimit: '—',
		lastSuccess: '—',
		lastError: 'Not configured',
		models: ['deepseek-chat', 'deepseek-reasoner'],
		history: [{ text: 'Provider scaffolded', time: '30d ago' }],
		config: {
			apiKey: '',
			secretKey: '',
			organizationId: '',
			baseUrl: 'https://api.deepseek.com',
			webhookUrl: '',
			redirectUri: '',
			scopes: 'chat',
			timeout: '40s',
			retryPolicy: '2 linear',
			defaultModel: 'deepseek-chat',
		},
	},
	{
		id: 'mistral',
		name: 'Mistral',
		badge: 'M',
		accent: 'from-[#ff7000] to-[#f97316]',
		status: 'disconnected',
		enabled: false,
		health: 'unknown',
		lastChecked: '2026-07-14 08:40',
		currentModel: 'mistral-large',
		endpoint: 'https://api.mistral.ai',
		apiVersion: 'v1',
		rateLimit: '—',
		lastSuccess: '—',
		lastError: 'Not configured',
		models: ['mistral-large', 'mistral-small'],
		history: [{ text: 'Awaiting platform key', time: '28d ago' }],
		config: {
			apiKey: '',
			secretKey: '',
			organizationId: '',
			baseUrl: 'https://api.mistral.ai',
			webhookUrl: '',
			redirectUri: '',
			scopes: 'chat',
			timeout: '35s',
			retryPolicy: '2 exponential',
			defaultModel: 'mistral-large',
		},
	},
	{
		id: 'grok',
		name: 'xAI Grok',
		badge: 'X',
		accent: 'from-[#111827] to-[#374151]',
		status: 'error',
		enabled: true,
		health: 'degraded',
		lastChecked: '2026-07-22 12:01',
		currentModel: 'grok-3',
		endpoint: 'https://api.x.ai/v1',
		apiVersion: 'v1',
		rateLimit: '600 RPM',
		lastSuccess: '2026-07-21 19:12',
		lastError: 'Timeout after 30s',
		models: ['grok-3', 'grok-2'],
		history: [
			{ text: 'Test connection failed (timeout)', time: '2h ago' },
			{ text: 'Provider enabled', time: '8d ago' },
		],
		config: {
			apiKey: 'xai-••••••••',
			secretKey: '',
			organizationId: '',
			baseUrl: 'https://api.x.ai/v1',
			webhookUrl: '',
			redirectUri: '',
			scopes: 'chat',
			timeout: '30s',
			retryPolicy: '3 exponential',
			defaultModel: 'grok-3',
		},
	},
	{
		id: 'replicate',
		name: 'Replicate',
		badge: 'R',
		accent: 'from-[#22c55e] to-[#16a34a]',
		status: 'disconnected',
		enabled: false,
		health: 'unknown',
		lastChecked: '2026-07-12 17:25',
		currentModel: 'black-forest-labs/flux',
		endpoint: 'https://api.replicate.com',
		apiVersion: 'v1',
		rateLimit: '—',
		lastSuccess: '—',
		lastError: 'Not configured',
		models: ['black-forest-labs/flux', 'stability-ai/sdxl'],
		history: [{ text: 'Image provider reserved', time: '35d ago' }],
		config: {
			apiKey: '',
			secretKey: '',
			organizationId: '',
			baseUrl: 'https://api.replicate.com',
			webhookUrl: '',
			redirectUri: '',
			scopes: 'predictions',
			timeout: '90s',
			retryPolicy: '2 exponential',
			defaultModel: 'black-forest-labs/flux',
		},
	},
	{
		id: 'fal',
		name: 'Fal.ai',
		badge: 'F',
		accent: 'from-[#ec4899] to-[#a855f7]',
		status: 'connected',
		enabled: true,
		health: 'healthy',
		lastChecked: '2026-07-22 14:05',
		currentModel: 'flux-pro',
		endpoint: 'https://fal.run',
		apiVersion: 'v1',
		rateLimit: '2,000 RPM',
		lastSuccess: '2026-07-22 14:04',
		lastError: '—',
		models: ['flux-pro', 'flux-dev', 'fast-sdxl'],
		history: [{ text: 'Image latency recovered', time: '5h ago' }],
		config: {
			apiKey: 'fal-••••••••',
			secretKey: '',
			organizationId: '',
			baseUrl: 'https://fal.run',
			webhookUrl: 'https://api.chef-ia.example/webhooks/fal',
			redirectUri: '',
			scopes: 'queue,sync',
			timeout: '60s',
			retryPolicy: '3 exponential',
			defaultModel: 'flux-pro',
		},
	},
	{
		id: 'pinterest',
		name: 'Pinterest Platform',
		badge: 'P',
		accent: 'from-[#E60023] to-[#B0001B]',
		status: 'connected',
		enabled: true,
		health: 'healthy',
		lastChecked: '2026-07-22 13:40',
		currentModel: 'OAuth app',
		endpoint: 'https://api.pinterest.com/v5',
		apiVersion: 'v5',
		rateLimit: '1,000 / day',
		lastSuccess: '2026-07-22 13:38',
		lastError: '—',
		models: ['boards', 'pins', 'oauth'],
		history: [{ text: 'OAuth redirect URI updated', time: '4d ago' }],
		config: {
			apiKey: 'app_••••',
			secretKey: 'sec_••••••••',
			organizationId: '',
			baseUrl: 'https://api.pinterest.com/v5',
			webhookUrl: '',
			redirectUri: 'https://app.chef-ia.example/oauth/pinterest/callback',
			scopes: 'boards:read,pins:write',
			timeout: '30s',
			retryPolicy: '2 linear',
			defaultModel: 'oauth',
		},
	},
	{
		id: 'wordpress',
		name: 'WordPress Platform',
		badge: 'WP',
		accent: 'from-[#21759b] to-[#135e96]',
		status: 'connected',
		enabled: true,
		health: 'healthy',
		lastChecked: '2026-07-22 13:20',
		currentModel: 'REST Application',
		endpoint: 'https://{site}/wp-json',
		apiVersion: 'wp/v2',
		rateLimit: 'Per-site',
		lastSuccess: '2026-07-22 12:55',
		lastError: '—',
		models: ['posts', 'media', 'categories'],
		history: [{ text: 'Application password template refreshed', time: '9d ago' }],
		config: {
			apiKey: '',
			secretKey: '',
			organizationId: '',
			baseUrl: 'https://{site}/wp-json',
			webhookUrl: '',
			redirectUri: '',
			scopes: 'posts,media',
			timeout: '25s',
			retryPolicy: '2 linear',
			defaultModel: 'wp/v2',
		},
	},
];

export const MOCK_MODELS = [
	{
		id: 'm1',
		name: 'gpt-4.1',
		provider: 'OpenAI',
		capability: 'text',
		contextWindow: 128000,
		inputCost: '$2.50 / 1M',
		outputCost: '$10.00 / 1M',
		isDefault: true,
		status: 'enabled',
		updated: '2026-07-18',
		version: '2026-04',
		capabilities: ['Article Writing', 'Recipe Writing', 'SEO', 'Summarization', 'Translation', 'Reasoning', 'Code Generation'],
		features: ['JSON mode', 'Tools', 'Streaming'],
		recommended: ['SEO articles', 'Recipe drafts', 'Prompt optimization'],
	},
	{
		id: 'm2',
		name: 'gpt-image-1',
		provider: 'OpenAI',
		capability: 'image',
		contextWindow: 32000,
		inputCost: '$5.00 / 1M',
		outputCost: '$—',
		isDefault: false,
		status: 'enabled',
		updated: '2026-07-10',
		version: '1.0',
		capabilities: ['Image Prompting', 'Image Generation'],
		features: ['Square', 'Portrait', 'Landscape'],
		recommended: ['Pinterest pins', 'Hero images'],
	},
	{
		id: 'm3',
		name: 'gemini-2.5-pro',
		provider: 'Google Gemini',
		capability: 'text',
		contextWindow: 1000000,
		inputCost: '$1.25 / 1M',
		outputCost: '$10.00 / 1M',
		isDefault: false,
		status: 'enabled',
		updated: '2026-07-20',
		version: '2.5',
		capabilities: ['Article Writing', 'SEO', 'Summarization', 'Reasoning', 'Translation'],
		features: ['Long context', 'Multimodal input'],
		recommended: ['Long-form research', 'Multi-source outlines'],
	},
	{
		id: 'm4',
		name: 'flux-pro',
		provider: 'Fal.ai',
		capability: 'image',
		contextWindow: 4096,
		inputCost: '$0.05 / image',
		outputCost: '$—',
		isDefault: true,
		status: 'enabled',
		updated: '2026-07-21',
		version: 'pro',
		capabilities: ['Image Prompting', 'Image Generation'],
		features: ['High fidelity', 'Fast queue'],
		recommended: ['Brand pins', 'Product lifestyle shots'],
	},
	{
		id: 'm5',
		name: 'claude-sonnet-4',
		provider: 'Anthropic Claude',
		capability: 'text',
		contextWindow: 200000,
		inputCost: '$3.00 / 1M',
		outputCost: '$15.00 / 1M',
		isDefault: false,
		status: 'disabled',
		updated: '2026-07-05',
		version: '4',
		capabilities: ['Article Writing', 'Recipe Writing', 'SEO', 'Reasoning', 'Summarization'],
		features: ['Tools', 'Streaming'],
		recommended: ['Editorial polish', 'Structured recipes'],
	},
	{
		id: 'm6',
		name: 'gemini-2.5-flash',
		provider: 'Google Gemini',
		capability: 'text',
		contextWindow: 1000000,
		inputCost: '$0.30 / 1M',
		outputCost: '$2.50 / 1M',
		isDefault: false,
		status: 'enabled',
		updated: '2026-07-19',
		version: '2.5-flash',
		capabilities: ['Summarization', 'Translation', 'SEO', 'Image Prompting'],
		features: ['Low latency', 'Streaming'],
		recommended: ['Meta descriptions', 'Pin captions'],
	},
	{
		id: 'm7',
		name: 'deepseek-chat',
		provider: 'DeepSeek',
		capability: 'text',
		contextWindow: 64000,
		inputCost: '$0.27 / 1M',
		outputCost: '$1.10 / 1M',
		isDefault: false,
		status: 'disabled',
		updated: '2026-06-28',
		version: 'v3',
		capabilities: ['Article Writing', 'Code Generation', 'Reasoning'],
		features: ['Streaming'],
		recommended: ['Draft generation', 'Outline expansion'],
	},
	{
		id: 'm8',
		name: 'grok-3',
		provider: 'xAI Grok',
		capability: 'text',
		contextWindow: 131072,
		inputCost: '$3.00 / 1M',
		outputCost: '$15.00 / 1M',
		isDefault: false,
		status: 'enabled',
		updated: '2026-07-15',
		version: '3',
		capabilities: ['Article Writing', 'Reasoning', 'Summarization'],
		features: ['Streaming', 'Tools'],
		recommended: ['Trend briefs', 'Idea exploration'],
	},
	{
		id: 'm9',
		name: 'mistral-large',
		provider: 'Mistral',
		capability: 'text',
		contextWindow: 128000,
		inputCost: '$2.00 / 1M',
		outputCost: '$6.00 / 1M',
		isDefault: false,
		status: 'disabled',
		updated: '2026-06-12',
		version: 'large',
		capabilities: ['Article Writing', 'Translation', 'Summarization', 'Code Generation'],
		features: ['Streaming'],
		recommended: ['Multilingual posts'],
	},
	{
		id: 'm10',
		name: 'flux-dev',
		provider: 'Fal.ai',
		capability: 'image',
		contextWindow: 4096,
		inputCost: '$0.025 / image',
		outputCost: '$—',
		isDefault: false,
		status: 'enabled',
		updated: '2026-07-14',
		version: 'dev',
		capabilities: ['Image Prompting', 'Image Generation'],
		features: ['Rapid iteration'],
		recommended: ['Concept exploration'],
	},
];

export const MOCK_LOGS = [
	{ id: 'l1', severity: 'info', message: 'Credits ledger synced', source: 'billing', at: '2026-07-22 14:02:11' },
	{ id: 'l2', severity: 'warn', message: 'Pinterest rate limit approaching', source: 'pinterest', at: '2026-07-22 13:48:02' },
	{ id: 'l3', severity: 'error', message: 'Image worker timeout on job #8821', source: 'workers', at: '2026-07-22 13:12:44' },
	{ id: 'l4', severity: 'info', message: 'New workspace created: Recipe Lab', source: 'auth', at: '2026-07-22 12:05:19' },
	{ id: 'l5', severity: 'debug', message: 'Queue drain cycle completed', source: 'queue', at: '2026-07-22 11:59:01' },
];

export const MOCK_QUEUE = {
	running: 7,
	waiting: 23,
	completed: 1482,
	failed: 12,
	retry: 4,
	jobs: [
		{ id: 'j1', name: 'Generate pin pack', status: 'running', workspace: 'Sunday Kitchen', age: '42s' },
		{ id: 'j2', name: 'Publish WordPress draft', status: 'waiting', workspace: 'Pin Atelier', age: '2m' },
		{ id: 'j3', name: 'Optimize prompts', status: 'completed', workspace: 'Agency North', age: '8m' },
		{ id: 'j4', name: 'Fal image render', status: 'failed', workspace: 'Recipe Lab', age: '14m' },
		{ id: 'j5', name: 'Credit top-up webhook', status: 'retry', workspace: 'Agency North', age: '3m' },
	],
};

export const MOCK_HEALTH = [
	{ name: 'API Status', status: 'healthy', detail: '99.98% uptime' },
	{ name: 'Database', status: 'healthy', detail: 'PocketBase primary' },
	{ name: 'Queue', status: 'degraded', detail: '23 waiting jobs' },
	{ name: 'Storage', status: 'healthy', detail: '68% capacity' },
	{ name: 'Workers', status: 'healthy', detail: '4 / 4 online' },
	{ name: 'Email', status: 'healthy', detail: 'SMTP ready' },
	{ name: 'AI Providers', status: 'healthy', detail: '3 connected' },
];

export const MOCK_ACTIVITY = [
	{ id: 'a1', text: 'Maya Chen upgraded to Pro', time: '12m ago' },
	{ id: 'a2', text: 'Fal.ai provider health check passed', time: '28m ago' },
	{ id: 'a3', text: 'Queue retry scheduled for job #8821', time: '41m ago' },
	{ id: 'a4', text: 'New registration: Jules Park', time: '1h ago' },
];

export const MOCK_ALERTS = [
	{ id: 'al1', tone: 'amber', text: 'Pinterest API approaching daily quota' },
	{ id: 'al2', tone: 'red', text: '12 failed image jobs in the last hour' },
	{ id: 'al3', tone: 'green', text: 'Maintenance window cleared' },
];

export const MOCK_PLANS = [
	{
		id: 'free',
		name: 'Free',
		price: 0,
		status: 'active',
		credits: 50,
		bonusCredits: 0,
		rollover: false,
		topupAllowed: false,
		subscribers: 420,
		avgUsage: 28,
		maxWorkspaces: 1,
		maxWordpress: 1,
		maxPinterest: 0,
		aiModels: 'Starter models',
		priorityQueue: false,
		support: 'Community',
		refillPolicy: 'Monthly reset · no rollover',
		publishingLimits: '10 publishes / mo',
		aiFeatures: 'AI Writer lite · basic pins',
		imageLimits: '10 images / mo',
		storageGb: 2,
		apiAccess: false,
		priorityProcessing: false,
		highlight: false,
	},
	{
		id: 'starter',
		name: 'Starter',
		price: 19,
		status: 'active',
		credits: 500,
		bonusCredits: 50,
		rollover: false,
		topupAllowed: true,
		subscribers: 268,
		avgUsage: 310,
		maxWorkspaces: 2,
		maxWordpress: 3,
		maxPinterest: 2,
		aiModels: 'Core text + image',
		priorityQueue: false,
		support: 'Email',
		refillPolicy: 'Monthly refill · unused expire',
		publishingLimits: '100 publishes / mo',
		aiFeatures: 'AI Writer · AI Pins · Image Generator',
		imageLimits: '200 images / mo',
		storageGb: 10,
		apiAccess: false,
		priorityProcessing: false,
		highlight: false,
	},
	{
		id: 'pro',
		name: 'Pro',
		price: 49,
		status: 'active',
		credits: 2000,
		bonusCredits: 200,
		rollover: true,
		topupAllowed: true,
		subscribers: 184,
		avgUsage: 1420,
		maxWorkspaces: 5,
		maxWordpress: 10,
		maxPinterest: 5,
		aiModels: 'All enabled models',
		priorityQueue: true,
		support: 'Priority email',
		refillPolicy: 'Monthly refill · 20% rollover cap',
		publishingLimits: '1,000 publishes / mo',
		aiFeatures: 'Full atelier suite + Brand Kit',
		imageLimits: '1,000 images / mo',
		storageGb: 50,
		apiAccess: true,
		priorityProcessing: true,
		highlight: true,
	},
	{
		id: 'business',
		name: 'Business',
		price: 129,
		status: 'active',
		credits: 8000,
		bonusCredits: 800,
		rollover: true,
		topupAllowed: true,
		subscribers: 52,
		avgUsage: 6100,
		maxWorkspaces: 20,
		maxWordpress: 40,
		maxPinterest: 20,
		aiModels: 'All models + early access',
		priorityQueue: true,
		support: 'Chat + email',
		refillPolicy: 'Monthly refill · 40% rollover cap',
		publishingLimits: 'Unlimited fair-use publishes',
		aiFeatures: 'Multi-brand kits · team seats',
		imageLimits: '5,000 images / mo',
		storageGb: 200,
		apiAccess: true,
		priorityProcessing: true,
		highlight: false,
	},
	{
		id: 'enterprise',
		name: 'Enterprise',
		price: 399,
		status: 'active',
		credits: 25000,
		bonusCredits: 2500,
		rollover: true,
		topupAllowed: true,
		subscribers: 12,
		avgUsage: 18400,
		maxWorkspaces: 'Custom',
		maxWordpress: 'Custom',
		maxPinterest: 'Custom',
		aiModels: 'Custom model routing',
		priorityQueue: true,
		support: 'Dedicated success',
		refillPolicy: 'Custom contract refill',
		publishingLimits: 'Custom SLA',
		aiFeatures: 'SSO-ready · custom workflows',
		imageLimits: 'Custom',
		storageGb: 1000,
		apiAccess: true,
		priorityProcessing: true,
		highlight: false,
	},
];
