export const MOCK_PLATFORM_ANALYTICS = {
	kpis: {
		today: {
			totalUsers: 1284,
			activeUsers: 418,
			newUsersToday: 14,
			totalWorkspaces: 912,
			activeWorkspaces: 764,
			articlesGenerated: 18420,
			imagesGenerated: 42110,
			pinterestPublications: 28940,
			wordpressPublications: 15680,
			creditsConsumed: 48290,
			mrr: 18420,
			arr: 221040,
		},
		'7d': {
			totalUsers: 1284,
			activeUsers: 1102,
			newUsersToday: 86,
			totalWorkspaces: 912,
			activeWorkspaces: 801,
			articlesGenerated: 1920,
			imagesGenerated: 4380,
			pinterestPublications: 3120,
			wordpressPublications: 1680,
			creditsConsumed: 12450,
			mrr: 18420,
			arr: 221040,
		},
		'30d': {
			totalUsers: 1284,
			activeUsers: 1188,
			newUsersToday: 312,
			totalWorkspaces: 912,
			activeWorkspaces: 840,
			articlesGenerated: 7840,
			imagesGenerated: 16920,
			pinterestPublications: 12110,
			wordpressPublications: 6420,
			creditsConsumed: 48290,
			mrr: 18420,
			arr: 221040,
		},
		'90d': {
			totalUsers: 1284,
			activeUsers: 1240,
			newUsersToday: 890,
			totalWorkspaces: 912,
			activeWorkspaces: 870,
			articlesGenerated: 22100,
			imagesGenerated: 48200,
			pinterestPublications: 34800,
			wordpressPublications: 18900,
			creditsConsumed: 128400,
			mrr: 18420,
			arr: 221040,
		},
	},
	charts: {
		userGrowth: [
			{ label: 'Jan', value: 42 },
			{ label: 'Feb', value: 48 },
			{ label: 'Mar', value: 55 },
			{ label: 'Apr', value: 61 },
			{ label: 'May', value: 70 },
			{ label: 'Jun', value: 78 },
			{ label: 'Jul', value: 88 },
		],
		dau: [
			{ label: 'Mon', value: 52 },
			{ label: 'Tue', value: 61 },
			{ label: 'Wed', value: 58 },
			{ label: 'Thu', value: 72 },
			{ label: 'Fri', value: 69 },
			{ label: 'Sat', value: 44 },
			{ label: 'Sun', value: 48 },
		],
		workspaceGrowth: [
			{ label: 'Jan', value: 38 },
			{ label: 'Feb', value: 44 },
			{ label: 'Mar', value: 51 },
			{ label: 'Apr', value: 57 },
			{ label: 'May', value: 66 },
			{ label: 'Jun', value: 74 },
			{ label: 'Jul', value: 82 },
		],
		articlesPerDay: [
			{ label: 'Mon', value: 64 },
			{ label: 'Tue', value: 71 },
			{ label: 'Wed', value: 68 },
			{ label: 'Thu', value: 80 },
			{ label: 'Fri', value: 76 },
			{ label: 'Sat', value: 42 },
			{ label: 'Sun', value: 39 },
		],
		imagesPerDay: [
			{ label: 'Mon', value: 70 },
			{ label: 'Tue', value: 78 },
			{ label: 'Wed', value: 74 },
			{ label: 'Thu', value: 86 },
			{ label: 'Fri', value: 81 },
			{ label: 'Sat', value: 55 },
			{ label: 'Sun', value: 50 },
		],
		creditsUsage: [
			{ label: 'W1', value: 48 },
			{ label: 'W2', value: 56 },
			{ label: 'W3', value: 62 },
			{ label: 'W4', value: 71 },
			{ label: 'W5', value: 68 },
			{ label: 'W6', value: 79 },
			{ label: 'W7', value: 84 },
		],
		revenueTrend: [
			{ label: 'Jan', value: 36 },
			{ label: 'Feb', value: 41 },
			{ label: 'Mar', value: 49 },
			{ label: 'Apr', value: 55 },
			{ label: 'May', value: 63 },
			{ label: 'Jun', value: 72 },
			{ label: 'Jul', value: 80 },
		],
		aiRequests: [
			{ label: 'Mon', value: 58 },
			{ label: 'Tue', value: 66 },
			{ label: 'Wed', value: 63 },
			{ label: 'Thu', value: 77 },
			{ label: 'Fri', value: 74 },
			{ label: 'Sat', value: 46 },
			{ label: 'Sun', value: 51 },
		],
	},
	providers: [
		{ name: 'OpenAI', requests: 8420, latency: '420ms', errorRate: '0.8%', credits: 18400, successRate: '99.2%', today: 312 },
		{ name: 'Gemini', requests: 4180, latency: '510ms', errorRate: '1.1%', credits: 9200, successRate: '98.9%', today: 148 },
		{ name: 'Claude', requests: 920, latency: '640ms', errorRate: '2.4%', credits: 2100, successRate: '97.6%', today: 12 },
		{ name: 'OpenRouter', requests: 640, latency: '780ms', errorRate: '3.1%', credits: 980, successRate: '96.9%', today: 8 },
		{ name: 'DeepSeek', requests: 410, latency: '560ms', errorRate: '1.6%', credits: 620, successRate: '98.4%', today: 5 },
		{ name: 'Mistral', requests: 280, latency: '590ms', errorRate: '2.0%', credits: 410, successRate: '98.0%', today: 3 },
		{ name: 'Grok', requests: 760, latency: '890ms', errorRate: '4.2%', credits: 1340, successRate: '95.8%', today: 18 },
		{ name: 'Replicate', requests: 540, latency: '1.2s', errorRate: '2.8%', credits: 780, successRate: '97.2%', today: 9 },
		{ name: 'Fal.ai', requests: 12640, latency: '380ms', errorRate: '0.6%', credits: 22100, successRate: '99.4%', today: 486 },
	],
	topModels: [
		{ model: 'flux-pro', provider: 'Fal.ai', requests: 9860, avgCost: '$0.05', responseTime: '1.8s', successRate: '99.4%' },
		{ model: 'gpt-4.1', provider: 'OpenAI', requests: 6420, avgCost: '$0.018', responseTime: '1.1s', successRate: '99.1%' },
		{ model: 'gemini-2.5-pro', provider: 'Gemini', requests: 3120, avgCost: '$0.012', responseTime: '1.4s', successRate: '98.8%' },
		{ model: 'gpt-image-1', provider: 'OpenAI', requests: 1980, avgCost: '$0.04', responseTime: '2.4s', successRate: '98.2%' },
		{ model: 'grok-3', provider: 'Grok', requests: 760, avgCost: '$0.022', responseTime: '1.6s', successRate: '95.8%' },
	],
	publishing: {
		wordpress: 15680,
		pinterest: 28940,
		facebook: 1240,
		scheduled: 860,
		failed: 214,
	},
	queue: {
		running: 7,
		queued: 23,
		completed: 1482,
		failed: 12,
		avgQueueTime: '48s',
	},
	subscriptions: {
		free: 420,
		starter: 268,
		pro: 184,
		business: 52,
		enterprise: 12,
		monthlyGrowth: '8.4%',
		conversionRate: '14.2%',
		churnRate: '2.1%',
	},
	system: [
		{ name: 'API Status', status: 'healthy', detail: '99.98% uptime' },
		{ name: 'Workers', status: 'healthy', detail: '4 / 4 online' },
		{ name: 'Queue', status: 'degraded', detail: '23 waiting' },
		{ name: 'Database', status: 'healthy', detail: 'PocketBase primary' },
		{ name: 'Storage', status: 'healthy', detail: '68% capacity' },
		{ name: 'Email', status: 'healthy', detail: 'SMTP ready' },
		{ name: 'Redis', status: 'healthy', detail: 'Cache hit 94%' },
		{ name: 'AI Providers', status: 'healthy', detail: '3 connected · 1 degraded' },
	],
	activity: [
		{ id: 'ra1', text: 'Jules Park registered', type: 'User registered', time: '12m ago' },
		{ id: 'ra2', text: 'Brunch Club workspace created', type: 'Workspace created', time: '28m ago' },
		{ id: 'ra3', text: 'Maya Chen upgraded to Pro', type: 'Subscription upgraded', time: '41m ago' },
		{ id: 'ra4', text: 'SEO article generated · Sunday Kitchen', type: 'Article generated', time: '1h ago' },
		{ id: 'ra5', text: 'Pin pack rendered via Fal.ai', type: 'Image generated', time: '1h ago' },
		{ id: 'ra6', text: '18 pins published to Agency Multi', type: 'Pinterest published', time: '2h ago' },
		{ id: 'ra7', text: 'WordPress draft synced · recipelab.io', type: 'WordPress published', time: '3h ago' },
		{ id: 'ra8', text: 'Grok timeout after 30s', type: 'Provider error', time: '4h ago' },
	],
};
