export const MOCK_PLATFORM_SETTINGS = {
	general: {
		platformName: 'Chef IA',
		supportEmail: 'support@chef-ia.example',
		defaultLanguage: 'en',
		timezone: 'UTC',
		dateFormat: 'YYYY-MM-DD',
		maintenanceMode: false,
		allowRegistration: true,
		defaultWorkspacePlan: 'free',
	},
	ai: {
		defaultProvider: 'OpenAI',
		defaultModel: 'gpt-4.1',
		fallbackProvider: 'Google Gemini',
		fallbackModel: 'gemini-2.5-flash',
		temperature: '0.7',
		topP: '0.9',
		maxTokens: '4096',
		streamingEnabled: true,
		reasoningEnabled: false,
	},
	content: {
		articleLength: '1200-1800 words',
		recipeStyle: 'Friendly food blog',
		seoEnabled: true,
		autoMetaDescription: true,
		autoSlug: true,
		autoCategories: true,
		autoTags: true,
		internalLinking: true,
	},
	images: {
		defaultImageProvider: 'Fal.ai',
		defaultImageModel: 'flux-pro',
		imageSize: '1080x1440',
		quality: 'high',
		storageProvider: 'Object Storage',
		compression: 'lossy-80',
		watermark: false,
	},
	wordpress: {
		publishingStatus: 'draft',
		retryPolicy: '3 exponential',
		featuredImageRequired: true,
		categories: 'Recipes, Tips',
		tags: 'pinterest, seo',
		autoPublish: false,
	},
	pinterest: {
		defaultBoard: 'New Pins',
		scheduling: 'smart-slots',
		retryPolicy: '2 linear',
		pinTemplate: 'Atelier Portrait',
		imageRatio: '2:3',
	},
	email: {
		smtpStatus: 'connected',
		senderName: 'Chef IA',
		senderEmail: 'noreply@chef-ia.example',
		dailyLimit: '5000',
		queueLimit: '250',
	},
	security: {
		sessionTimeout: '7 days',
		passwordPolicy: 'min 10 · upper · number · symbol',
		require2fa: false,
		apiRateLimit: '120 / min',
		allowedOrigins: 'https://app.chef-ia.example, https://admin.chef-ia.example',
	},
	system: {
		logRetention: '90 days',
		backupSchedule: 'Daily 02:00 UTC',
		cacheTtl: '15 minutes',
		storageLimit: '2 TB',
		defaultRegion: 'eu-west-1',
	},
	featureFlags: [
		{ id: 'ai-writer', label: 'AI Writer', enabled: true },
		{ id: 'ai-images', label: 'AI Images', enabled: true },
		{ id: 'templates', label: 'Templates', enabled: true },
		{ id: 'brand-kit', label: 'Brand Kit', enabled: true },
		{ id: 'analytics', label: 'Analytics', enabled: true },
		{ id: 'pinterest', label: 'Pinterest', enabled: true },
		{ id: 'wordpress', label: 'WordPress', enabled: true },
		{ id: 'calendar', label: 'Calendar', enabled: true },
		{ id: 'history', label: 'History', enabled: true },
		{ id: 'api-access', label: 'API Access', enabled: false },
	],
	license: {
		currentVersion: '0.0.0',
		buildNumber: '2026.07.22.1',
		licenseStatus: 'Active',
		releaseChannel: 'stable',
	},
};
