export const MOCK_QUEUE_MONITOR = {
	summary: {
		running: 7,
		queued: 23,
		completedToday: 1482,
		failed: 12,
		retry: 4,
		avgProcessingTime: '48s',
		workersOnline: '4 / 5',
		jobsPerMinute: 18,
	},
	health: {
		avgQueueTime: '1m 12s',
		longestWaiting: 'job_9912 · 14m',
		oldestRunning: 'job_9901 · 6m 40s',
		queueCapacity: '62%',
		workerUtilization: '78%',
	},
	jobs: [
		{
			id: 'job_9901',
			type: 'AI Article Generation',
			workspace: 'Sunday Kitchen',
			owner: 'Leo Martins',
			provider: 'OpenAI',
			model: 'gpt-4.1',
			priority: 'high',
			status: 'running',
			progress: 68,
			worker: 'worker-a3',
			created: '2026-07-22 15:02:11',
			started: '2026-07-22 15:02:40',
			duration: '6m 40s',
			credits: 12,
			retries: 0,
			failureReason: '—',
			inputs: { topic: 'Summer brunch recipes', tone: 'Friendly' },
			outputs: { draftId: 'art_8841', words: 1840 },
			timeline: [
				{ text: 'Job enqueued', time: '15:02:11' },
				{ text: 'Worker claimed job', time: '15:02:40' },
				{ text: 'Outline generated', time: '15:04:02' },
				{ text: 'Drafting sections…', time: '15:06:18' },
			],
			logs: [
				'[info] prompt packed (2.1k tokens)',
				'[info] model=gpt-4.1 latency=1.1s',
				'[info] section 3/5 complete',
			],
		},
		{
			id: 'job_9902',
			type: 'Image Generation',
			workspace: 'Recipe Lab',
			owner: 'Maya Chen',
			provider: 'Fal.ai',
			model: 'flux-pro',
			priority: 'normal',
			status: 'running',
			progress: 42,
			worker: 'worker-b1',
			created: '2026-07-22 15:05:02',
			started: '2026-07-22 15:05:20',
			duration: '3m 12s',
			credits: 8,
			retries: 0,
			failureReason: '—',
			inputs: { prompt: 'Flat-lay brunch board', size: '1080x1440' },
			outputs: { imageUrl: 'pending' },
			timeline: [
				{ text: 'Job enqueued', time: '15:05:02' },
				{ text: 'Fal queue accepted', time: '15:05:20' },
			],
			logs: [
				'[info] fal.submit flux-pro',
				'[info] rendering frame 2/5',
			],
		},
		{
			id: 'job_9903',
			type: 'Pinterest Publishing',
			workspace: 'Agency North',
			owner: 'Amina Costa',
			provider: 'Pinterest',
			model: '—',
			priority: 'high',
			status: 'queued',
			progress: 0,
			worker: '—',
			created: '2026-07-22 15:06:44',
			started: '—',
			duration: '—',
			credits: 0,
			retries: 0,
			failureReason: '—',
			inputs: { pins: 18, board: 'Client Pack A' },
			outputs: {},
			timeline: [{ text: 'Waiting for publisher slot', time: '15:06:44' }],
			logs: ['[info] queued behind 4 publish jobs'],
		},
		{
			id: 'job_9904',
			type: 'WordPress Publishing',
			workspace: 'Pin Atelier',
			owner: 'Sofia Reis',
			provider: 'WordPress',
			model: '—',
			priority: 'normal',
			status: 'waiting',
			progress: 0,
			worker: '—',
			created: '2026-07-22 14:58:10',
			started: '—',
			duration: '—',
			credits: 0,
			retries: 0,
			failureReason: '—',
			inputs: { postId: 'wp_221', site: 'pinatelier.blog' },
			outputs: {},
			timeline: [{ text: 'Awaiting WordPress auth refresh', time: '14:58:10' }],
			logs: ['[warn] token refresh scheduled'],
		},
		{
			id: 'job_9905',
			type: 'Bulk Publishing',
			workspace: 'Brunch Club',
			owner: 'Elena Duarte',
			provider: 'Pinterest',
			model: '—',
			priority: 'low',
			status: 'completed',
			progress: 100,
			worker: 'worker-c2',
			created: '2026-07-22 14:20:01',
			started: '2026-07-22 14:20:33',
			duration: '4m 02s',
			credits: 24,
			retries: 0,
			failureReason: '—',
			inputs: { batch: 36 },
			outputs: { published: 36, failed: 0 },
			timeline: [
				{ text: 'Batch accepted', time: '14:20:01' },
				{ text: 'Completed', time: '14:24:35' },
			],
			logs: ['[info] published 36/36 pins'],
		},
		{
			id: 'job_9906',
			type: 'SEO Optimization',
			workspace: 'Recipes App',
			owner: 'Jules Park',
			provider: 'Gemini',
			model: 'gemini-2.5-flash',
			priority: 'normal',
			status: 'completed',
			progress: 100,
			worker: 'worker-a3',
			created: '2026-07-22 13:40:12',
			started: '2026-07-22 13:40:40',
			duration: '1m 18s',
			credits: 3,
			retries: 0,
			failureReason: '—',
			inputs: { articleId: 'art_7712' },
			outputs: { titleScore: 92, metaReady: true },
			timeline: [{ text: 'Completed', time: '13:41:58' }],
			logs: ['[info] meta + FAQ rewritten'],
		},
		{
			id: 'job_9907',
			type: 'Template Rendering',
			workspace: 'Spice Route Media',
			owner: 'Omar Vidal',
			provider: 'Fal.ai',
			model: 'flux-dev',
			priority: 'normal',
			status: 'failed',
			progress: 20,
			worker: 'worker-b1',
			created: '2026-07-22 13:12:00',
			started: '2026-07-22 13:12:18',
			duration: '26s',
			credits: 1,
			retries: 1,
			failureReason: 'Image worker timeout on job #8821',
			inputs: { templateId: 'tpl_44' },
			outputs: {},
			timeline: [
				{ text: 'Started render', time: '13:12:18' },
				{ text: 'Failed · timeout', time: '13:12:44' },
			],
			logs: ['[error] fal timeout after 30s', '[warn] moved to retry queue'],
		},
		{
			id: 'job_9908',
			type: 'Recipe Generation',
			workspace: 'Sunday Kitchen',
			owner: 'Leo Martins',
			provider: 'OpenAI',
			model: 'gpt-4.1',
			priority: 'high',
			status: 'retrying',
			progress: 15,
			worker: 'worker-a3',
			created: '2026-07-22 12:55:30',
			started: '2026-07-22 15:01:02',
			duration: '—',
			credits: 4,
			retries: 2,
			failureReason: 'Upstream 429 rate limit',
			inputs: { cuisine: 'Portuguese', servings: 4 },
			outputs: {},
			timeline: [
				{ text: 'First attempt failed', time: '12:56:10' },
				{ text: 'Retry #2 started', time: '15:01:02' },
			],
			logs: ['[warn] rate limited', '[info] backoff 90s applied'],
		},
		{
			id: 'job_9909',
			type: 'Import',
			workspace: 'Agency North',
			owner: 'Amina Costa',
			provider: '—',
			model: '—',
			priority: 'low',
			status: 'paused',
			progress: 55,
			worker: 'worker-c2',
			created: '2026-07-22 11:10:00',
			started: '2026-07-22 11:10:40',
			duration: '—',
			credits: 0,
			retries: 0,
			failureReason: '—',
			inputs: { file: 'clients-csv-v3.csv', rows: 240 },
			outputs: { imported: 132 },
			timeline: [{ text: 'Paused by operator', time: '11:28:00' }],
			logs: ['[info] paused at row 132'],
		},
		{
			id: 'job_9910',
			type: 'Export',
			workspace: 'Recipe Lab',
			owner: 'Maya Chen',
			provider: '—',
			model: '—',
			priority: 'normal',
			status: 'cancelled',
			progress: 0,
			worker: '—',
			created: '2026-07-22 10:02:11',
			started: '—',
			duration: '—',
			credits: 0,
			retries: 0,
			failureReason: 'Cancelled by owner',
			inputs: { format: 'csv', scope: 'pins' },
			outputs: {},
			timeline: [{ text: 'Cancelled before start', time: '10:03:01' }],
			logs: ['[info] cancel acknowledged'],
		},
		{
			id: 'job_9911',
			type: 'Webhook Delivery',
			workspace: 'Brunch Club',
			owner: 'Elena Duarte',
			provider: '—',
			model: '—',
			priority: 'high',
			status: 'completed',
			progress: 100,
			worker: 'worker-d4',
			created: '2026-07-22 09:44:00',
			started: '2026-07-22 09:44:02',
			duration: '1.2s',
			credits: 0,
			retries: 0,
			failureReason: '—',
			inputs: { event: 'publish.completed' },
			outputs: { statusCode: 200 },
			timeline: [{ text: 'Delivered', time: '09:44:03' }],
			logs: ['[info] HTTP 200 from customer endpoint'],
		},
		{
			id: 'job_9912',
			type: 'Email Notification',
			workspace: 'Pin Atelier',
			owner: 'Sofia Reis',
			provider: '—',
			model: '—',
			priority: 'low',
			status: 'queued',
			progress: 0,
			worker: '—',
			created: '2026-07-22 08:50:00',
			started: '—',
			duration: '—',
			credits: 0,
			retries: 0,
			failureReason: '—',
			inputs: { template: 'welcome', to: 'sofia@pins.co' },
			outputs: {},
			timeline: [{ text: 'Waiting in mail queue', time: '08:50:00' }],
			logs: ['[info] smtp queue depth 14'],
		},
	],
	activity: [
		{ id: 'qa1', text: 'job_9901 started on worker-a3', kind: 'Jobs starting', time: '6m ago' },
		{ id: 'qa2', text: 'Bulk publishing completed · Brunch Club', kind: 'Publishing completed', time: '12m ago' },
		{ id: 'qa3', text: 'job_9907 failed · Fal timeout', kind: 'Failures', time: '2h ago' },
		{ id: 'qa4', text: 'job_9908 retrying after rate limit', kind: 'Retries', time: '8m ago' },
		{ id: 'qa5', text: 'worker-d4 came online', kind: 'Workers online/offline', time: '25m ago' },
		{ id: 'qa6', text: 'job_9905 finished in 4m 02s', kind: 'Jobs finishing', time: '1h ago' },
	],
	workers: [
		{ id: 'worker-a3', status: 'online', currentJob: 'job_9901', cpu: '62%', memory: '71%', jobsToday: 186, avgTime: '41s' },
		{ id: 'worker-b1', status: 'online', currentJob: 'job_9902', cpu: '78%', memory: '64%', jobsToday: 142, avgTime: '1m 08s' },
		{ id: 'worker-c2', status: 'online', currentJob: '—', cpu: '22%', memory: '48%', jobsToday: 98, avgTime: '36s' },
		{ id: 'worker-d4', status: 'online', currentJob: '—', cpu: '18%', memory: '41%', jobsToday: 74, avgTime: '29s' },
		{ id: 'worker-e5', status: 'offline', currentJob: '—', cpu: '0%', memory: '0%', jobsToday: 0, avgTime: '—' },
	],
};
