export const MOCK_SYSTEM_HEALTH = {
	overall: {
		status: 'healthy',
		uptime: '99.97%',
		lastIncident: '2026-07-21 19:12 · Grok timeout spike',
		lastCheck: '2026-07-22 16:35:02',
	},
	summary: {
		systemUptime: '42d 11h',
		servicesOnline: 18,
		servicesOffline: 1,
		avgResponseTime: '186ms',
		cpuUsage: '47%',
		memoryUsage: '68%',
		diskUsage: '61%',
		networkLatency: '24ms',
	},
	coreServices: [
		{ name: 'Frontend', status: 'healthy', responseTime: '42ms', lastChecked: '16:35:01', uptime: '99.99%', version: 'web@0.0.0' },
		{ name: 'Backend API', status: 'healthy', responseTime: '118ms', lastChecked: '16:35:01', uptime: '99.98%', version: 'api@0.0.0' },
		{ name: 'PocketBase', status: 'healthy', responseTime: '36ms', lastChecked: '16:35:00', uptime: '99.99%', version: '0.22.x' },
		{ name: 'Redis', status: 'healthy', responseTime: '4ms', lastChecked: '16:34:58', uptime: '99.95%', version: '7.2' },
		{ name: 'Job Queue', status: 'warning', responseTime: '210ms', lastChecked: '16:34:59', uptime: '99.91%', version: 'queue-v3' },
		{ name: 'Storage', status: 'healthy', responseTime: '88ms', lastChecked: '16:34:55', uptime: '99.97%', version: 's3-compat' },
		{ name: 'Email Service', status: 'healthy', responseTime: '320ms', lastChecked: '16:34:50', uptime: '99.90%', version: 'smtp-bridge' },
		{ name: 'Scheduler', status: 'healthy', responseTime: '55ms', lastChecked: '16:35:00', uptime: '99.96%', version: 'cron-2' },
	],
	aiProviders: [
		{ name: 'OpenAI', status: 'healthy', avgResponse: '420ms', lastSuccess: '16:34:48', errorRate: '0.8%', quota: '72% remaining' },
		{ name: 'Gemini', status: 'healthy', avgResponse: '510ms', lastSuccess: '16:34:12', errorRate: '1.1%', quota: '81% remaining' },
		{ name: 'Claude', status: 'warning', avgResponse: '—', lastSuccess: '—', errorRate: '—', quota: 'Not configured' },
		{ name: 'OpenRouter', status: 'warning', avgResponse: '—', lastSuccess: '—', errorRate: '—', quota: 'Not configured' },
		{ name: 'DeepSeek', status: 'warning', avgResponse: '—', lastSuccess: '—', errorRate: '—', quota: 'Not configured' },
		{ name: 'Mistral', status: 'warning', avgResponse: '—', lastSuccess: '—', errorRate: '—', quota: 'Not configured' },
		{ name: 'Grok', status: 'critical', avgResponse: '890ms', lastSuccess: '15:01:02', errorRate: '4.2%', quota: '64% remaining' },
		{ name: 'Replicate', status: 'warning', avgResponse: '1.2s', lastSuccess: '14:20:00', errorRate: '2.8%', quota: '88% remaining' },
		{ name: 'Fal.ai', status: 'healthy', avgResponse: '380ms', lastSuccess: '16:34:55', errorRate: '0.6%', quota: '69% remaining' },
	],
	external: [
		{ name: 'WordPress', status: 'healthy', detail: 'REST application passwords OK' },
		{ name: 'Pinterest', status: 'healthy', detail: 'OAuth v5 · quota normal' },
		{ name: 'SMTP', status: 'healthy', detail: 'Delivery latency 320ms' },
		{ name: 'Webhook Service', status: 'healthy', detail: '99.4% delivery success' },
		{ name: 'Object Storage', status: 'healthy', detail: '68% capacity' },
		{ name: 'CDN', status: 'healthy', detail: 'Edge hit ratio 91%' },
	],
	resources: {
		cpu: [
			{ label: '00', value: 32 },
			{ label: '04', value: 28 },
			{ label: '08', value: 44 },
			{ label: '12', value: 58 },
			{ label: '16', value: 47 },
			{ label: '20', value: 39 },
			{ label: '24', value: 35 },
		],
		memory: [
			{ label: '00', value: 61 },
			{ label: '04', value: 60 },
			{ label: '08', value: 64 },
			{ label: '12', value: 70 },
			{ label: '16', value: 68 },
			{ label: '20', value: 66 },
			{ label: '24', value: 63 },
		],
		disk: [
			{ label: 'Mon', value: 55 },
			{ label: 'Tue', value: 56 },
			{ label: 'Wed', value: 57 },
			{ label: 'Thu', value: 58 },
			{ label: 'Fri', value: 59 },
			{ label: 'Sat', value: 60 },
			{ label: 'Sun', value: 61 },
		],
		bandwidth: [
			{ label: 'Mon', value: 42 },
			{ label: 'Tue', value: 48 },
			{ label: 'Wed', value: 51 },
			{ label: 'Thu', value: 63 },
			{ label: 'Fri', value: 58 },
			{ label: 'Sat', value: 36 },
			{ label: 'Sun', value: 33 },
		],
		storageGrowth: [
			{ label: 'Jan', value: 38 },
			{ label: 'Feb', value: 42 },
			{ label: 'Mar', value: 47 },
			{ label: 'Apr', value: 51 },
			{ label: 'May', value: 55 },
			{ label: 'Jun', value: 58 },
			{ label: 'Jul', value: 61 },
		],
	},
	certificates: [
		{ service: 'Frontend', domain: 'app.chef-ia.example', status: 'valid', expires: '2026-11-12', days: 113 },
		{ service: 'API', domain: 'api.chef-ia.example', status: 'valid', expires: '2026-11-12', days: 113 },
		{ service: 'CDN', domain: 'cdn.chef-ia.example', status: 'valid', expires: '2026-09-02', days: 42 },
		{ service: 'Admin', domain: 'admin.chef-ia.example', status: 'expiring', expires: '2026-08-08', days: 17 },
	],
	incidents: [
		{ id: 'i1', text: 'Grok provider timeouts elevated', type: 'Provider outages', time: 'Yesterday 19:12' },
		{ id: 'i2', text: 'Queue depth recovered under 25', type: 'Recoveries', time: 'Yesterday 20:04' },
		{ id: 'i3', text: 'Scheduled storage maintenance window', type: 'Maintenance', time: 'Jul 18 02:00' },
		{ id: 'i4', text: 'Brief API latency spike (p95 480ms)', type: 'Service interruptions', time: 'Jul 15 11:22' },
		{ id: 'i5', text: 'SMTP bridge recovered', type: 'Recoveries', time: 'Jul 12 09:40' },
	],
	alerts: [
		{ id: 'a1', severity: 'warning', service: 'Job Queue', message: '23 jobs waiting · capacity 62%', started: '16:10', status: 'open' },
		{ id: 'a2', severity: 'critical', service: 'Grok', message: 'Error rate above 4%', started: '15:01', status: 'open' },
		{ id: 'a3', severity: 'info', service: 'SSL', message: 'admin.chef-ia.example expires in 17 days', started: '08:00', status: 'acknowledged' },
	],
	logs: [
		'[16:35:02] health.check completed · overall=healthy',
		'[16:34:59] queue.depth=23 workers.online=4/5',
		'[16:34:55] fal.health ok latency=380ms',
		'[16:34:48] openai.health ok latency=420ms',
		'[16:20:11] alert.opened service=Job Queue severity=warning',
		'[15:01:08] alert.opened service=Grok severity=critical',
		'[14:55:00] redis.ping ok 4ms',
		'[14:40:22] pocketbase.backup snapshot ok',
	],
};
