/** Default plan catalog for Admin Plans & Credits. */

export const DEFAULT_LIMITS = {
	articlesPerMonth: 0,
	imagesPerMonth: 0,
	aiRequests: 0,
	pinterestAccounts: 0,
	wordpressSites: 0,
	teamMembers: 1,
	storageGb: 1,
	queueJobs: 0,
	exports: 0,
	apiRequests: 0,
	maxWorkspaces: 1,
};

export const DEFAULT_FEATURES = {
	aiWriter: false,
	aiImages: false,
	templates: false,
	brandKit: false,
	analytics: false,
	calendar: false,
	pinterest: false,
	wordpress: false,
	history: false,
	apiAccess: false,
	priorityQueue: false,
};

export const PLAN_SEED_CATALOG = [
	{
		name: 'Free',
		slug: 'free',
		description: 'Get started with Chef IA basics.',
		monthly_price: 0,
		yearly_price: 0,
		currency: 'USD',
		active: true,
		display_order: 10,
		credits: 50,
		bonus_credits: 0,
		rollover: false,
		topup_allowed: false,
		support: 'Community',
		refill_policy: 'Monthly reset · no rollover',
		publishing_limits: '10 publishes / mo',
		ai_features: 'AI Writer lite · basic pins',
		image_limits: '10 images / mo',
		ai_models: 'Starter models',
		highlight: false,
		status: 'active',
		limits: {
			...DEFAULT_LIMITS,
			articlesPerMonth: 10,
			imagesPerMonth: 10,
			aiRequests: 50,
			wordpressSites: 1,
			storageGb: 2,
			queueJobs: 20,
			exports: 5,
			maxWorkspaces: 1,
		},
		features: {
			...DEFAULT_FEATURES,
			aiWriter: true,
			history: true,
		},
		seedSubscribers: [
			{ workspace_key: 'kitchen-dev', workspace_name: 'Kitchen Dev', owner_email: 'noah@kitchen.dev', credits_balance: 0, status: 'canceled' },
		],
		avgUsage: 28,
	},
	{
		name: 'Starter',
		slug: 'starter',
		description: 'For growing food blogs.',
		monthly_price: 19,
		yearly_price: 190,
		currency: 'USD',
		active: true,
		display_order: 20,
		credits: 500,
		bonus_credits: 50,
		rollover: false,
		topup_allowed: true,
		support: 'Email',
		refill_policy: 'Monthly refill · unused expire',
		publishing_limits: '100 publishes / mo',
		ai_features: 'AI Writer · AI Pins · Image Generator',
		image_limits: '200 images / mo',
		ai_models: 'Core text + image',
		highlight: false,
		status: 'active',
		limits: {
			...DEFAULT_LIMITS,
			articlesPerMonth: 100,
			imagesPerMonth: 200,
			aiRequests: 500,
			pinterestAccounts: 2,
			wordpressSites: 3,
			teamMembers: 2,
			storageGb: 10,
			queueJobs: 200,
			exports: 50,
			apiRequests: 1000,
			maxWorkspaces: 2,
		},
		features: {
			...DEFAULT_FEATURES,
			aiWriter: true,
			aiImages: true,
			templates: true,
			pinterest: true,
			wordpress: true,
			history: true,
			calendar: true,
		},
		seedSubscribers: [
			{ workspace_key: 'pin-atelier', workspace_name: 'Pin Atelier', owner_email: 'sofia@pins.co', credits_balance: 890, status: 'trialing' },
		],
		avgUsage: 310,
	},
	{
		name: 'Pro',
		slug: 'pro',
		description: 'Full atelier suite for serious publishers.',
		monthly_price: 49,
		yearly_price: 490,
		currency: 'USD',
		active: true,
		display_order: 30,
		credits: 2000,
		bonus_credits: 200,
		rollover: true,
		topup_allowed: true,
		support: 'Priority email',
		refill_policy: 'Monthly refill · 20% rollover cap',
		publishing_limits: '1,000 publishes / mo',
		ai_features: 'Full atelier suite + Brand Kit',
		image_limits: '1,000 images / mo',
		ai_models: 'All enabled models',
		highlight: true,
		status: 'active',
		limits: {
			...DEFAULT_LIMITS,
			articlesPerMonth: 1000,
			imagesPerMonth: 1000,
			aiRequests: 2000,
			pinterestAccounts: 5,
			wordpressSites: 10,
			teamMembers: 5,
			storageGb: 50,
			queueJobs: 2000,
			exports: 200,
			apiRequests: 10000,
			maxWorkspaces: 5,
		},
		features: {
			aiWriter: true,
			aiImages: true,
			templates: true,
			brandKit: true,
			analytics: true,
			calendar: true,
			pinterest: true,
			wordpress: true,
			history: true,
			apiAccess: true,
			priorityQueue: true,
		},
		seedSubscribers: [
			{ workspace_key: 'sunday-kitchen', workspace_name: 'Sunday Kitchen', owner_email: 'leo@foodblog.io', credits_balance: 4200, status: 'active' },
		],
		avgUsage: 1420,
	},
	{
		name: 'Business',
		slug: 'business',
		description: 'Multi-brand teams and agencies.',
		monthly_price: 129,
		yearly_price: 1290,
		currency: 'USD',
		active: true,
		display_order: 40,
		credits: 8000,
		bonus_credits: 800,
		rollover: true,
		topup_allowed: true,
		support: 'Chat + email',
		refill_policy: 'Monthly refill · 40% rollover cap',
		publishing_limits: 'Unlimited fair-use publishes',
		ai_features: 'Multi-brand kits · team seats',
		image_limits: '5,000 images / mo',
		ai_models: 'All models + early access',
		highlight: false,
		status: 'active',
		limits: {
			...DEFAULT_LIMITS,
			articlesPerMonth: 5000,
			imagesPerMonth: 5000,
			aiRequests: 8000,
			pinterestAccounts: 20,
			wordpressSites: 40,
			teamMembers: 20,
			storageGb: 200,
			queueJobs: 10000,
			exports: 1000,
			apiRequests: 50000,
			maxWorkspaces: 20,
		},
		features: {
			aiWriter: true,
			aiImages: true,
			templates: true,
			brandKit: true,
			analytics: true,
			calendar: true,
			pinterest: true,
			wordpress: true,
			history: true,
			apiAccess: true,
			priorityQueue: true,
		},
		seedSubscribers: [
			{ workspace_key: 'agency-north', workspace_name: 'Agency North', owner_email: 'amina@example.com', credits_balance: 22000, status: 'active' },
		],
		avgUsage: 6100,
	},
	{
		name: 'Enterprise',
		slug: 'enterprise',
		description: 'Custom limits, routing, and support.',
		monthly_price: 399,
		yearly_price: 3990,
		currency: 'USD',
		active: true,
		display_order: 50,
		credits: 25000,
		bonus_credits: 2500,
		rollover: true,
		topup_allowed: true,
		support: 'Dedicated',
		refill_policy: 'Custom refill · negotiated rollover',
		publishing_limits: 'Custom SLA publishes',
		ai_features: 'Custom workflows · SSO-ready',
		image_limits: 'Custom image pool',
		ai_models: 'Custom model routing',
		highlight: false,
		status: 'active',
		limits: {
			...DEFAULT_LIMITS,
			articlesPerMonth: 999999,
			imagesPerMonth: 999999,
			aiRequests: 999999,
			pinterestAccounts: 999999,
			wordpressSites: 999999,
			teamMembers: 999999,
			storageGb: 2000,
			queueJobs: 999999,
			exports: 999999,
			apiRequests: 999999,
			maxWorkspaces: 999999,
		},
		features: {
			aiWriter: true,
			aiImages: true,
			templates: true,
			brandKit: true,
			analytics: true,
			calendar: true,
			pinterest: true,
			wordpress: true,
			history: true,
			apiAccess: true,
			priorityQueue: true,
		},
		seedSubscribers: [],
		avgUsage: 18400,
	},
];
