/**
 * P1-13 — WordPress publish enqueue idempotency race protection.
 * Run: node --test src/services/wordpress-publish.enqueue-idempotency.test.js
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, it } from 'node:test';
import {
	buildAutoGeneratedPublishIdempotencyKey,
	clientSuppliedIdempotencyKey,
	createPublishJobIdempotent,
	findPublishJobByOwnerIdempotencyKey,
	isPublishJobIdempotencyUniqueViolation,
} from './wordpress-publish-enqueue-idempotency.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../../..');

function mapPublishJob(job) {
	return {
		id: job.id,
		idempotencyKey: job.idempotency_key || '',
		title: job.title,
		status: job.status,
	};
}

function createMockPocketbase(initialJobs = []) {
	const jobs = initialJobs.map((job) => ({ ...job }));
	const ownerKeys = new Set(
		jobs.map((job) => `${job.owner}\0${job.idempotency_key}`),
	);

	return {
		jobs,
		filter(template, params = {}) {
			return { template: String(template), params: { ...params } };
		},
		collection(name) {
			if (name !== 'publish_jobs') {
				throw new Error(`unexpected collection ${name}`);
			}
			return {
				async getFirstListItem(filterObj) {
					const params = filterObj?.params || {};
					const owner = String(params.owner || '');
					const key = String(params.key || '');
					const found = jobs.find((job) => job.owner === owner && job.idempotency_key === key);
					if (!found) {
						const err = new Error('The requested resource was not found.');
						err.status = 404;
						throw err;
					}
					return { ...found };
				},
				async create(body) {
					const owner = String(body.owner || '');
					const key = String(body.idempotency_key || '');
					const composite = `${owner}\0${key}`;
					if (ownerKeys.has(composite)) {
						const err = new Error('Failed to create record: UNIQUE constraint failed: idx_publish_jobs_owner_idempotency');
						err.data = { code: 'validation_not_unique' };
						throw err;
					}
					const row = {
						id: `job_${jobs.length + 1}`,
						...body,
						created: new Date().toISOString(),
						updated: new Date().toISOString(),
					};
					jobs.push(row);
					ownerKeys.add(composite);
					return { ...row };
				},
			};
		},
	};
}

describe('wordpress publish enqueue idempotency (P1-13)', () => {
	it('A. returns existing job when owner + idempotency_key already exists', async () => {
		const pb = createMockPocketbase([
			{
				id: 'job-existing',
				owner: 'O1',
				idempotency_key: 'K1',
				site: 'site-1',
				title: 'Existing',
				content: 'Body',
				wp_status: 'publish',
				status: 'queued',
			},
		]);

		const first = mapPublishJob(await findPublishJobByOwnerIdempotencyKey('O1', 'K1', pb));
		const second = mapPublishJob(await findPublishJobByOwnerIdempotencyKey('O1', 'K1', pb));

		assert.equal(first.id, 'job-existing');
		assert.equal(second.id, 'job-existing');
		assert.equal(first.idempotencyKey, 'K1');
		assert.equal(pb.jobs.length, 1);
	});

	it('B. recovers from unique constraint violation by returning the existing job', async () => {
		const pb = createMockPocketbase([
			{
				id: 'job-a',
				owner: 'O1',
				idempotency_key: 'K1',
				site: 'site-1',
				title: 'First',
				content: 'Body',
				wp_status: 'publish',
				status: 'queued',
			},
		]);

		const createBody = {
			owner: 'O1',
			idempotency_key: 'K1',
			site: 'site-1',
			title: 'Second',
			content: 'Body',
			wp_status: 'publish',
			status: 'queued',
		};

		const job = await createPublishJobIdempotent('O1', 'K1', createBody, pb);
		const mapped = mapPublishJob(job);

		assert.equal(mapped.id, 'job-a');
		assert.equal(mapped.title, 'First');
		assert.equal(pb.jobs.length, 1);
	});

	it('C. rethrows non-unique database errors', async () => {
		const pb = {
			filter: (_template, params = {}) => ({ template: String(_template), params: { ...params } }),
			collection: () => ({
				create: async () => {
					throw new Error('database disk I/O error');
				},
			}),
		};

		await assert.rejects(
			() => createPublishJobIdempotent('O1', 'K1', { owner: 'O1', idempotency_key: 'K1' }, pb),
			(err) => err instanceof Error && err.message === 'database disk I/O error',
		);
		assert.equal(isPublishJobIdempotencyUniqueViolation(new Error('database disk I/O error')), false);
		assert.equal(
			isPublishJobIdempotencyUniqueViolation(new Error('UNIQUE constraint failed: idx_publish_jobs_owner_idempotency')),
			true,
		);
	});

	it('D. auto-generated keys remain unique and do not false-dedupe', () => {
		assert.equal(clientSuppliedIdempotencyKey({}), '');
		assert.equal(clientSuppliedIdempotencyKey({ clientToken: 'token-1' }), 'token-1');
		assert.equal(clientSuppliedIdempotencyKey({ idempotencyKey: 'key-1' }), 'key-1');

		const keyA = buildAutoGeneratedPublishIdempotencyKey('O1', 'site-1', 'aaaa1111', 1000);
		const keyB = buildAutoGeneratedPublishIdempotencyKey('O1', 'site-1', 'bbbb2222', 2000);

		assert.notEqual(keyA, keyB);
		assert.match(keyA, /^wp-O1-site-1-/);
	});

	it('D2. independent requests without client keys create separate jobs', async () => {
		const pb = createMockPocketbase([]);

		const bodyA = {
			owner: 'O1',
			idempotency_key: buildAutoGeneratedPublishIdempotencyKey('O1', 'site-1', 'aaaa1111', 1000),
			site: 'site-1',
			title: 'A',
			content: 'Body',
			wp_status: 'publish',
			status: 'queued',
		};
		const bodyB = {
			owner: 'O1',
			idempotency_key: buildAutoGeneratedPublishIdempotencyKey('O1', 'site-1', 'bbbb2222', 2000),
			site: 'site-1',
			title: 'B',
			content: 'Body',
			wp_status: 'publish',
			status: 'queued',
		};

		const jobA = await createPublishJobIdempotent('O1', bodyA.idempotency_key, bodyA, pb);
		const jobB = await createPublishJobIdempotent('O1', bodyB.idempotency_key, bodyB, pb);

		assert.notEqual(jobA.id, jobB.id);
		assert.equal(pb.jobs.length, 2);
	});

	it('E. enqueueWordpressPublish still forwards req into resolvePublishSite (P1-4)', () => {
		const source = readFileSync(path.join(root, 'apps/api/src/services/wordpress-publish.js'), 'utf8');
		assert.match(source, /ownerOrCtx\?\.req/);
		assert.match(source, /req:\s*ctx\.req/);
		assert.match(source, /resolvePublishSite\([\s\S]*?req:\s*ctx\.req/);
		assert.match(source, /createPublishJobIdempotent\(/);
	});

	it('F. P1-5/P1-6/P1-12 regression sources remain intact', () => {
		const publishSource = readFileSync(path.join(root, 'apps/api/src/services/wordpress-publish.js'), 'utf8');
		const queueSource = readFileSync(path.join(root, 'apps/api/src/services/wordpress-publish-queue.js'), 'utf8');
		const rollupSource = readFileSync(path.join(root, 'apps/api/src/services/wordpress-publish-analytics-rollup.js'), 'utf8');

		assert.match(publishSource, /recordBelongsToWorkspace\(job, req\)/);
		assert.match(publishSource, /rollupWordpressPublishAnalytics/);
		assert.match(queueSource, /persistWordpressPostIdentity/);
		assert.match(rollupSource, /export function rollupWordpressPublishAnalytics/);
	});

	it('migration defines unique owner+idempotency index and dedupe repair keys', () => {
		const migration = readFileSync(
			path.join(root, 'apps/pocketbase/pb_migrations/1786020000_publish_jobs_idempotency_unique.js'),
			'utf8',
		);
		assert.match(migration, /idx_publish_jobs_owner_idempotency/);
		assert.match(migration, /CREATE UNIQUE INDEX/);
		assert.match(migration, /owner.*idempotency_key|idempotency_key.*owner/);
		assert.match(migration, /dedupePublishJobOwnerIdempotencyKeys/);
		assert.match(migration, /wp-dedupe-/);
	});
});
