/**
 * P1-13 + WP-P0-1 — WordPress publish enqueue idempotency.
 * Run: node --test src/services/wordpress-publish.enqueue-idempotency.test.js
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, it } from 'node:test';
import {
	buildAutoGeneratedPublishIdempotencyKey,
	clientSuppliedIdempotencyKey,
	createPublishJobIdempotent,
	findPublishJobByOwnerWorkspaceIdempotencyKey,
	isPublishJobIdempotencyUniqueViolation,
	requireWordpressPublishIdempotencyWorkspace,
	WORDPRESS_PUBLISH_IDEMPOTENCY_WORKSPACE_REQUIRED_MESSAGE,
	wordpressPublishWaitJobIsVisible,
} from './wordpress-publish-enqueue-idempotency.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../../..');

function mapPublishJob(job) {
	return {
		id: job.id,
		idempotencyKey: job.idempotency_key || '',
		title: job.title,
		status: job.status,
		workspace: job.workspace || '',
	};
}

function createMockPocketbase(initialJobs = []) {
	const jobs = initialJobs.map((job) => ({ ...job }));
	const ownerWorkspaceKeys = new Set(
		jobs.map((job) => `${job.owner}\0${job.workspace || ''}\0${job.idempotency_key}`),
	);

	return {
		jobs,
		filter(template, params = {}) {
			return { template: String(template), params: { ...params } };
		},
		collection(name) {
			if (name !== 'publish_jobs') {
				throw new Error(`unexpected collection ${name}`);
			}
			return {
				async getFirstListItem(filterObj) {
					const params = filterObj?.params || {};
					const owner = String(params.owner || '');
					const workspace = String(params.workspace || '');
					const key = String(params.key || '');
					const found = jobs.find((job) => (
						job.owner === owner
						&& String(job.workspace || '') === workspace
						&& job.idempotency_key === key
					));
					if (!found) {
						const err = new Error('The requested resource was not found.');
						err.status = 404;
						throw err;
					}
					return { ...found };
				},
				async create(body) {
					const owner = String(body.owner || '');
					const workspace = String(body.workspace || '');
					const key = String(body.idempotency_key || '');
					const composite = `${owner}\0${workspace}\0${key}`;
					if (ownerWorkspaceKeys.has(composite)) {
						const err = new Error('Failed to create record: UNIQUE constraint failed: idx_publish_jobs_owner_workspace_idempotency');
						err.data = { code: 'validation_not_unique' };
						throw err;
					}
					const row = {
						id: `job_${jobs.length + 1}`,
						...body,
						created: new Date().toISOString(),
						updated: new Date().toISOString(),
					};
					jobs.push(row);
					ownerWorkspaceKeys.add(composite);
					return { ...row };
				},
			};
		},
	};
}

describe('wordpress publish enqueue idempotency (P1-13)', () => {
	it('A. returns existing job when owner + workspace + idempotency_key already exists', async () => {
		const pb = createMockPocketbase([
			{
				id: 'job-existing',
				owner: 'O1',
				workspace: 'ws-a',
				idempotency_key: 'K1',
				site: 'site-1',
				title: 'Existing',
				content: 'Body',
				wp_status: 'publish',
				status: 'queued',
			},
		]);

		const first = mapPublishJob(await findPublishJobByOwnerWorkspaceIdempotencyKey({
			ownerId: 'O1',
			workspaceId: 'ws-a',
			idempotencyKey: 'K1',
		}, pb));
		const second = mapPublishJob(await findPublishJobByOwnerWorkspaceIdempotencyKey({
			ownerId: 'O1',
			workspaceId: 'ws-a',
			idempotencyKey: 'K1',
		}, pb));

		assert.equal(first.id, 'job-existing');
		assert.equal(second.id, 'job-existing');
		assert.equal(first.idempotencyKey, 'K1');
		assert.equal(pb.jobs.length, 1);
	});

	it('B. recovers from unique constraint violation by returning the existing job', async () => {
		const pb = createMockPocketbase([
			{
				id: 'job-a',
				owner: 'O1',
				workspace: 'ws-a',
				idempotency_key: 'K1',
				site: 'site-1',
				title: 'First',
				content: 'Body',
				wp_status: 'publish',
				status: 'queued',
			},
		]);

		const createBody = {
			owner: 'O1',
			workspace: 'ws-a',
			idempotency_key: 'K1',
			site: 'site-1',
			title: 'Second',
			content: 'Body',
			wp_status: 'publish',
			status: 'queued',
		};

		const job = await createPublishJobIdempotent({
			ownerId: 'O1',
			workspaceId: 'ws-a',
			idempotencyKey: 'K1',
		}, createBody, pb);
		const mapped = mapPublishJob(job);

		assert.equal(mapped.id, 'job-a');
		assert.equal(mapped.title, 'First');
		assert.equal(pb.jobs.length, 1);
	});

	it('C. rethrows non-unique database errors', async () => {
		const pb = {
			filter: (_template, params = {}) => ({ template: String(_template), params: { ...params } }),
			collection: () => ({
				create: async () => {
					throw new Error('database disk I/O error');
				},
			}),
		};

		await assert.rejects(
			() => createPublishJobIdempotent({
				ownerId: 'O1',
				workspaceId: 'ws-a',
				idempotencyKey: 'K1',
			}, { owner: 'O1', workspace: 'ws-a', idempotency_key: 'K1' }, pb),
			(err) => err instanceof Error && err.message === 'database disk I/O error',
		);
		assert.equal(isPublishJobIdempotencyUniqueViolation(new Error('database disk I/O error')), false);
		assert.equal(
			isPublishJobIdempotencyUniqueViolation(new Error('UNIQUE constraint failed: idx_publish_jobs_owner_workspace_idempotency')),
			true,
		);
		assert.equal(
			isPublishJobIdempotencyUniqueViolation(new Error('UNIQUE constraint failed: idx_publish_jobs_owner_idempotency')),
			true,
		);
	});

	it('D. auto-generated keys remain unique and do not false-dedupe', () => {
		assert.equal(clientSuppliedIdempotencyKey({}), '');
		assert.equal(clientSuppliedIdempotencyKey({ clientToken: 'token-1' }), 'token-1');
		assert.equal(clientSuppliedIdempotencyKey({ idempotencyKey: 'key-1' }), 'key-1');

		const keyA = buildAutoGeneratedPublishIdempotencyKey('O1', 'site-1', 'aaaa1111', 1000);
		const keyB = buildAutoGeneratedPublishIdempotencyKey('O1', 'site-1', 'bbbb2222', 2000);

		assert.notEqual(keyA, keyB);
		assert.match(keyA, /^wp-O1-site-1-/);
	});

	it('D2. independent requests without client keys create separate jobs', async () => {
		const pb = createMockPocketbase([]);

		const bodyA = {
			owner: 'O1',
			workspace: 'ws-a',
			idempotency_key: buildAutoGeneratedPublishIdempotencyKey('O1', 'site-1', 'aaaa1111', 1000),
			site: 'site-1',
			title: 'A',
			content: 'Body',
			wp_status: 'publish',
			status: 'queued',
		};
		const bodyB = {
			owner: 'O1',
			workspace: 'ws-a',
			idempotency_key: buildAutoGeneratedPublishIdempotencyKey('O1', 'site-1', 'bbbb2222', 2000),
			site: 'site-1',
			title: 'B',
			content: 'Body',
			wp_status: 'publish',
			status: 'queued',
		};

		const jobA = await createPublishJobIdempotent({
			ownerId: 'O1',
			workspaceId: 'ws-a',
			idempotencyKey: bodyA.idempotency_key,
		}, bodyA, pb);
		const jobB = await createPublishJobIdempotent({
			ownerId: 'O1',
			workspaceId: 'ws-a',
			idempotencyKey: bodyB.idempotency_key,
		}, bodyB, pb);

		assert.notEqual(jobA.id, jobB.id);
		assert.equal(pb.jobs.length, 2);
	});

	it('E. enqueueWordpressPublish still forwards req into resolvePublishSite (P1-4)', () => {
		const source = readFileSync(path.join(root, 'apps/api/src/services/wordpress-publish.js'), 'utf8');
		assert.match(source, /ownerOrCtx\?\.req/);
		assert.match(source, /req:\s*ctx\.req/);
		assert.match(source, /resolvePublishSite\([\s\S]*?req:\s*ctx\.req/);
		assert.match(source, /createPublishJobIdempotent\(/);
	});

	it('F. P1-5/P1-6/P1-12 regression sources remain intact', () => {
		const publishSource = readFileSync(path.join(root, 'apps/api/src/services/wordpress-publish.js'), 'utf8');
		const queueSource = readFileSync(path.join(root, 'apps/api/src/services/wordpress-publish-queue.js'), 'utf8');
		const rollupSource = readFileSync(path.join(root, 'apps/api/src/services/wordpress-publish-analytics-rollup.js'), 'utf8');

		assert.match(publishSource, /recordBelongsToWorkspace\(job, req\)/);
		assert.match(publishSource, /rollupWordpressPublishAnalytics/);
		assert.match(queueSource, /persistWordpressPostIdentity/);
		assert.match(rollupSource, /export function rollupWordpressPublishAnalytics/);
	});

	it('historical P1-13 migration still defines unique owner+idempotency index', () => {
		const migration = readFileSync(
			path.join(root, 'apps/pocketbase/pb_migrations/1786020000_publish_jobs_idempotency_unique.js'),
			'utf8',
		);
		assert.match(migration, /idx_publish_jobs_owner_idempotency/);
		assert.match(migration, /CREATE UNIQUE INDEX/);
		assert.match(migration, /owner.*idempotency_key|idempotency_key.*owner/);
		assert.match(migration, /dedupePublishJobOwnerIdempotencyKeys/);
		assert.match(migration, /wp-dedupe-/);
	});
});

describe('WordPress enqueue idempotency workspace isolation (WP-P0-1)', () => {
	const WS_A = 'ws-a';
	const WS_B = 'ws-b';
	const OWNER = 'O1';

	it('same owner, WS-A job + K1: WS-B lookup does not return the WS-A job', async () => {
		const pb = createMockPocketbase([
			{
				id: 'job-a',
				owner: OWNER,
				workspace: WS_A,
				idempotency_key: 'K1',
				title: 'WS-A post',
				status: 'queued',
			},
		]);

		await assert.rejects(
			() => findPublishJobByOwnerWorkspaceIdempotencyKey({
				ownerId: OWNER,
				workspaceId: WS_B,
				idempotencyKey: 'K1',
			}, pb),
			(err) => err.status === 404,
		);

		const created = await createPublishJobIdempotent({
			ownerId: OWNER,
			workspaceId: WS_B,
			idempotencyKey: 'K1',
		}, {
			owner: OWNER,
			workspace: WS_B,
			idempotency_key: 'K1',
			title: 'WS-B post',
			status: 'queued',
		}, pb);

		assert.equal(created.id !== 'job-a', true);
		assert.equal(created.workspace, WS_B);
		assert.equal(created.title, 'WS-B post');
		assert.equal(pb.jobs.length, 2);
	});

	it('same workspace replay with K1 returns the same job', async () => {
		const pb = createMockPocketbase([
			{
				id: 'job-a',
				owner: OWNER,
				workspace: WS_A,
				idempotency_key: 'K1',
				title: 'Original',
				status: 'queued',
			},
		]);

		const existing = await findPublishJobByOwnerWorkspaceIdempotencyKey({
			ownerId: OWNER,
			workspaceId: WS_A,
			idempotencyKey: 'K1',
		}, pb);
		const recovered = await createPublishJobIdempotent({
			ownerId: OWNER,
			workspaceId: WS_A,
			idempotencyKey: 'K1',
		}, {
			owner: OWNER,
			workspace: WS_A,
			idempotency_key: 'K1',
			title: 'Retry',
			status: 'queued',
		}, pb);

		assert.equal(existing.id, 'job-a');
		assert.equal(recovered.id, 'job-a');
		assert.equal(recovered.title, 'Original');
		assert.equal(pb.jobs.length, 1);
	});

	it('unique-violation recovery is workspace-scoped', async () => {
		const pb = createMockPocketbase([
			{
				id: 'job-a',
				owner: OWNER,
				workspace: WS_A,
				idempotency_key: 'K1',
				title: 'WS-A',
				status: 'queued',
			},
			{
				id: 'job-b',
				owner: OWNER,
				workspace: WS_B,
				idempotency_key: 'K1',
				title: 'WS-B',
				status: 'queued',
			},
		]);

		const recovered = await createPublishJobIdempotent({
			ownerId: OWNER,
			workspaceId: WS_A,
			idempotencyKey: 'K1',
		}, {
			owner: OWNER,
			workspace: WS_A,
			idempotency_key: 'K1',
			title: 'WS-A retry',
			status: 'queued',
		}, pb);

		assert.equal(recovered.id, 'job-a');
		assert.equal(recovered.title, 'WS-A');
		assert.equal(recovered.workspace, WS_A);
	});

	it('missing workspace fails closed and never owner-only lookups', () => {
		assert.throws(
			() => requireWordpressPublishIdempotencyWorkspace(''),
			(err) => err.status === 422
				&& err.errorCode === 'WORDPRESS_PUBLISH_IDEMPOTENCY_WORKSPACE_REQUIRED'
				&& err.message === WORDPRESS_PUBLISH_IDEMPOTENCY_WORKSPACE_REQUIRED_MESSAGE,
		);
		assert.throws(
			() => requireWordpressPublishIdempotencyWorkspace('   '),
			(err) => err.status === 422,
		);
	});

	it('create and find fail closed when workspace is missing', async () => {
		const pb = createMockPocketbase([
			{
				id: 'job-a',
				owner: OWNER,
				workspace: WS_A,
				idempotency_key: 'K1',
				title: 'WS-A',
				status: 'queued',
			},
		]);

		await assert.rejects(
			() => findPublishJobByOwnerWorkspaceIdempotencyKey({
				ownerId: OWNER,
				workspaceId: '',
				idempotencyKey: 'K1',
			}, pb),
			(err) => err.status === 422 && err.errorCode === 'WORDPRESS_PUBLISH_IDEMPOTENCY_WORKSPACE_REQUIRED',
		);
		await assert.rejects(
			() => createPublishJobIdempotent({
				ownerId: OWNER,
				workspaceId: '',
				idempotencyKey: 'K1',
			}, { owner: OWNER, idempotency_key: 'K1' }, pb),
			(err) => err.status === 422,
		);
		assert.equal(pb.jobs.length, 1);
	});

	it('waitForJobResult cannot return a foreign-workspace job', () => {
		const jobA = {
			id: 'job-a',
			owner: OWNER,
			workspace: WS_A,
			status: 'published',
			wp_post_url: 'https://ws-a.example/post',
		};
		const jobB = {
			id: 'job-b',
			owner: OWNER,
			workspace: WS_B,
			status: 'published',
			wp_post_url: 'https://ws-b.example/post',
		};

		assert.equal(wordpressPublishWaitJobIsVisible(jobA, { ownerId: OWNER, workspaceId: WS_A }), true);
		assert.equal(wordpressPublishWaitJobIsVisible(jobB, { ownerId: OWNER, workspaceId: WS_A }), false);
		assert.equal(wordpressPublishWaitJobIsVisible(jobA, { ownerId: OWNER, workspaceId: '' }), false);
		assert.equal(wordpressPublishWaitJobIsVisible(null, { ownerId: OWNER, workspaceId: WS_A }), false);
	});
});

describe('WordPress enqueue idempotency workspace isolation (WP-P0-1 static)', () => {
	const seam = readFileSync(path.join(root, 'apps/api/src/services/wordpress-publish-enqueue-idempotency.js'), 'utf8');
	const publish = readFileSync(path.join(root, 'apps/api/src/services/wordpress-publish.js'), 'utf8');
	const routes = readFileSync(path.join(root, 'apps/api/src/routes/wordpress/index.js'), 'utf8');
	const newMigration = readFileSync(
		path.join(root, 'apps/pocketbase/pb_migrations/1786700000_publish_jobs_workspace_idempotency_unique.js'),
		'utf8',
	);
	const oldMigration = readFileSync(
		path.join(root, 'apps/pocketbase/pb_migrations/1786020000_publish_jobs_idempotency_unique.js'),
		'utf8',
	);

	it('idempotency lookup is owner + workspace + key, never owner-only', () => {
		assert.match(seam, /owner = \{\:owner\} && workspace = \{\:workspace\} && idempotency_key = \{\:key\}/);
		assert.doesNotMatch(seam, /owner = \{\:owner\} && idempotency_key = \{\:key\}/);
		assert.doesNotMatch(publish, /findPublishJobByOwnerIdempotencyKey\(/);
		assert.doesNotMatch(seam, /findPublishJobByOwnerIdempotencyKey\(/);
		assert.match(publish, /findPublishJobByOwnerWorkspaceIdempotencyKey/);
		assert.match(publish, /requireWordpressPublishIdempotencyWorkspace/);
		assert.match(seam, /export function requireWordpressPublishIdempotencyWorkspace/);
	});

	it('unique-violation recovery uses the same workspace-scoped lookup', () => {
		assert.match(seam, /createPublishJobIdempotent/);
		assert.match(seam, /findPublishJobByOwnerWorkspaceIdempotencyKey\(\{[\s\S]*workspaceId: workspace/);
	});

	it('new migration replaces owner-only unique with owner+workspace+key', () => {
		assert.match(newMigration, /idx_publish_jobs_owner_workspace_idempotency/);
		assert.match(
			newMigration,
			/CREATE UNIQUE INDEX `idx_publish_jobs_owner_workspace_idempotency` ON `publish_jobs` \(`owner`, `workspace`, `idempotency_key`\)/,
		);
		assert.match(newMigration, /indexesWithoutMarker\(jobs, PUBLISH_JOBS_OWNER_IDEMPOTENCY_INDEX_MARKER\)/);
		assert.match(newMigration, /idx_publish_jobs_owner_idempotency/);
		assert.doesNotMatch(oldMigration, /idx_publish_jobs_owner_workspace_idempotency/);
		assert.match(oldMigration, /idx_publish_jobs_owner_idempotency/);
	});

	it('waitForJobResult uses request workspace scope and getPublishJob with req', () => {
		assert.match(routes, /waitForJobResult\(req, job\.id\)/);
		assert.match(routes, /wordpressPublishWaitJobIsVisible\(job, \{ ownerId, workspaceId \}\)/);
		assert.match(routes, /getPublishJob\(ownerId, jobId, req\)/);
		assert.doesNotMatch(routes, /waitForJobResult\(wordpressJobOwner\(req\), job\.id\)/);
		assert.doesNotMatch(routes, /getPublishJob\(ownerId, jobId\);/);
	});
});
