import { randomBytes } from 'node:crypto';
import pocketbaseClient from '../utils/pocketbaseClient.js';
import { httpError } from '../middleware/require-admin.js';
import { mapWpStatus, assertWordpressStatusAllowed, wordpressCapabilitiesFromKeys } from './wordpress-client.js';
import { resolvePublishSite } from './wordpress-sites.js';
import { newWorkflowId } from './publish-pipeline.js';
import { logWorkflowStep } from './workspace-notify.js';
import { sanitizeCollectionPayload } from '../utils/pocketbase-safe-query.js';
import { resolveJobCreateStamps } from './queue/job-ownership.js';
import { andWorkspaceScope, recordBelongsToWorkspace } from './workspace-ownership.js';
import { rollupWordpressPublishAnalytics } from './wordpress-publish-analytics-rollup.js';
import {
	buildAutoGeneratedPublishIdempotencyKey,
	clientSuppliedIdempotencyKey,
	createPublishJobIdempotent,
	findPublishJobByOwnerWorkspaceIdempotencyKey,
	requireWordpressPublishIdempotencyWorkspace,
} from './wordpress-publish-enqueue-idempotency.js';
import { syncArticleToDraftOnPublishAbort } from './wordpress-article-status-sync.js';
import { sanitizeWriterImagesSnapshot } from './wordpress-writer-media.js';

export {
	buildAutoGeneratedPublishIdempotencyKey,
	clientSuppliedIdempotencyKey,
	createPublishJobIdempotent,
	findPublishJobByOwnerWorkspaceIdempotencyKey,
	isPublishJobIdempotencyUniqueViolation,
	requireWordpressPublishIdempotencyWorkspace,
	wordpressPublishWaitJobIsVisible,
} from './wordpress-publish-enqueue-idempotency.js';

export { rollupWordpressPublishAnalytics } from './wordpress-publish-analytics-rollup.js';

async function loadOwnedPublishJob(ownerId, jobId, req = null) {
	const job = await pocketbaseClient.collection('publish_jobs').getOne(jobId).catch(() => null);
	if (!job || job.owner !== ownerId) {
		throw httpError(404, 'Publish job not found', 'NOT_FOUND');
	}
	if (req && !recordBelongsToWorkspace(job, req)) {
		throw httpError(404, 'Publish job not found', 'NOT_FOUND');
	}
	return job;
}

function buildOwnerScopedFilter(ownerId, req, extraFilter = '') {
	if (req) {
		return andWorkspaceScope(req, extraFilter);
	}
	const extra = String(extraFilter || '').trim();
	if (!extra) {
		return pocketbaseClient.filter('owner = {:owner}', { owner: ownerId });
	}
	return `${pocketbaseClient.filter('owner = {:owner}', { owner: ownerId })} && (${extra})`;
}

function asStringArray(value) {
	if (!value) return [];
	if (Array.isArray(value)) {
		return value.map((item) => String(item).trim()).filter(Boolean);
	}
	if (typeof value === 'string') {
		return value.split(',').map((item) => item.trim()).filter(Boolean);
	}
	return [];
}

export function mapPublishJob(job) {
	return {
		id: job.id,
		siteId: job.site,
		articleId: job.article_id || null,
		title: job.title,
		excerpt: job.excerpt || '',
		slug: job.slug || '',
		wpStatus: job.wp_status,
		status: job.status,
		progress: Number(job.progress) || 0,
		attemptCount: Number(job.attempt_count) || 0,
		maxAttempts: Number(job.max_attempts) || 3,
		scheduledAt: job.scheduled_at || null,
		timezone: job.timezone || 'UTC',
		startedAt: job.started_at || null,
		completedAt: job.completed_at || null,
		lastError: job.last_error || '',
		errorCode: (job.payload && typeof job.payload === 'object' && job.payload.lastErrorCode)
			? String(job.payload.lastErrorCode)
			: '',
		wpPostId: job.wp_post_id || null,
		wpPostUrl: job.wp_post_url || '',
		wpMediaId: job.wp_media_id || null,
		mediaIds: job.media_ids || [],
		deadLetter: Boolean(job.dead_letter),
		idempotencyKey: job.idempotency_key || '',
		created: job.created,
		updated: job.updated,
	};
}

export function mapPublishHistory(row) {
	return {
		id: row.id,
		jobId: row.job || null,
		siteId: row.site || null,
		title: row.title || '',
		wpStatus: row.wp_status || '',
		result: row.result || '',
		wpPostId: row.wp_post_id || null,
		publishedUrl: row.published_url || '',
		publishedAt: row.published_at || null,
		durationMs: Number(row.duration_ms) || 0,
		error: row.error || '',
		meta: row.meta || {},
		created: row.created,
	};
}

export async function enqueueWordpressPublish(ownerOrCtx, payload = {}) {
	const ctx = typeof ownerOrCtx === 'string'
		? { ownerId: ownerOrCtx, workspaceId: '', workspaceKey: '', req: null }
		: {
			ownerId: ownerOrCtx?.ownerId || '',
			workspaceId: ownerOrCtx?.workspaceId || '',
			workspaceKey: ownerOrCtx?.workspaceKey || '',
			req: ownerOrCtx?.req || null,
		};
	const ownerId = String(ctx.ownerId || '').trim();
	if (!ownerId) throw httpError(422, 'owner is required', 'VALIDATION_ERROR');

	const siteId = payload.siteId || payload.websiteId;
	const { site } = await resolvePublishSite({
		ownerId,
		siteId,
		websiteId: payload.websiteId,
		req: ctx.req,
	});

	const stamps = await resolveJobCreateStamps({
		ownerId,
		workspaceId: ctx.workspaceId,
		workspaceKey: ctx.workspaceKey,
		site,
	});
	const workspaceId = requireWordpressPublishIdempotencyWorkspace(stamps.workspace || ctx.workspaceId);

	const title = String(payload.title || '').trim();
	const content = String(payload.content || '').trim();
	if (!title) throw httpError(422, 'title is required', 'VALIDATION_ERROR');
	if (!content) throw httpError(422, 'content is required', 'VALIDATION_ERROR');

	const scheduledAt = payload.scheduledAt || payload.scheduled_at || null;
	const wpStatus = mapWpStatus(payload.status || payload.wpStatus || 'draft', scheduledAt);

	const cachedCapabilityKeys = site?.health?.capabilities;
	if (Array.isArray(cachedCapabilityKeys) && cachedCapabilityKeys.length) {
		assertWordpressStatusAllowed(
			{ capabilities: wordpressCapabilitiesFromKeys(cachedCapabilityKeys), name: site.name || site.url },
			wpStatus,
			site.name || site.url || ownerId,
		);
	}

	const immediate = !scheduledAt && wpStatus !== 'future';
	const clientKey = clientSuppliedIdempotencyKey(payload);
	const idempotencyKey = clientKey
		|| buildAutoGeneratedPublishIdempotencyKey(ownerId, site.id, randomBytes(4).toString('hex'));

	if (clientKey) {
		try {
			const existing = await findPublishJobByOwnerWorkspaceIdempotencyKey({
				ownerId,
				workspaceId,
				idempotencyKey,
			}, pocketbaseClient);
			return mapPublishJob(existing);
		} catch {
			// continue
		}
	}

	const workflowId = String(payload.workflowId || payload.workflow_id || '').trim() || newWorkflowId();
	const writerImagesSnapshot = sanitizeWriterImagesSnapshot(payload.writerImages);

	const createBody = await sanitizeCollectionPayload({
		collection: 'publish_jobs',
		context: 'wordpress:enqueue-publish',
		requiredKeys: ['owner', 'site', 'title', 'content', 'wp_status', 'status'],
		payload: {
			owner: stamps.owner || ownerId,
			workspace: workspaceId,
			workspace_key: stamps.workspace_key || ctx.workspaceKey || '',
			site: site.id,
			article_id: payload.articleId || payload.article_id || '',
			title,
			content,
			excerpt: String(payload.excerpt || '').slice(0, 5000),
			slug: String(payload.slug || '').slice(0, 300),
			meta_description: String(payload.metaDescription || payload.meta_description || '').slice(0, 1000),
			featured_image_url: String(payload.featuredImageUrl || payload.featured_image_url || payload.featuredImage || '').slice(0, 2000),
			categories: asStringArray(payload.categories || payload.category || payload.wpCategory),
			tags: asStringArray(payload.tags),
			seo: payload.seo && typeof payload.seo === 'object' ? payload.seo : {},
			recipe_card: payload.recipeCard || payload.recipe_card || null,
			payload: {
				updatePostId: payload.postId || payload.wpPostId || null,
				contentType: String(payload.contentType || payload.type || 'post').toLowerCase() === 'page' ? 'page' : 'post',
				authorId: payload.authorId || payload.author || null,
				enqueuePinterest: payload.enqueuePinterest !== false,
				websiteId: site.website || payload.websiteId || '',
				workflowId,
				...(writerImagesSnapshot ? { writerImages: writerImagesSnapshot } : {}),
				writerMediaMap: { bySlotId: {}, bySourceUrl: {} },
			},
			workflow_id: workflowId,
			enqueue_pinterest: payload.enqueuePinterest !== false,
			wp_status: wpStatus,
			scheduled_at: scheduledAt || '',
			timezone: payload.timezone || 'UTC',
			status: immediate ? 'queued' : 'scheduled',
			progress: 0,
			attempt_count: 0,
			max_attempts: Number(payload.maxAttempts) || 3,
			next_retry_at: '',
			last_error: '',
			idempotency_key: idempotencyKey,
			dead_letter: false,
			claim_token: '',
			claim_version: 0,
			media_ids: [],
		},
	});

	const job = await createPublishJobIdempotent({
		ownerId,
		workspaceId,
		idempotencyKey,
	}, createBody, pocketbaseClient);

	await logWorkflowStep({
		ownerId,
		action: 'workflow.enqueued',
		resourceType: 'publish_jobs',
		resourceId: job.id,
		metadata: {
			workflowId,
			siteId: site.id,
			immediate,
			enqueuePinterest: payload.enqueuePinterest !== false,
		},
	});

	return mapPublishJob(job);
}

export async function listPublishJobs(ownerId, query = {}, req = null) {
	const page = Math.max(1, Number(query.page) || 1);
	const perPage = Math.min(100, Math.max(1, Number(query.perPage) || 20));
	const status = String(query.status || '').trim();
	const statusFilter = status
		? pocketbaseClient.filter('status = {:status}', { status })
		: '';
	const filter = buildOwnerScopedFilter(ownerId, req, statusFilter);
	const result = await pocketbaseClient.collection('publish_jobs').getList(page, perPage, {
		filter,
		sort: '-created',
		requestKey: null,
	}).catch(() => ({ items: [], page: 1, perPage, totalItems: 0, totalPages: 0 }));

	return {
		items: result.items.map(mapPublishJob),
		page: result.page,
		perPage: result.perPage,
		totalItems: result.totalItems,
		totalPages: result.totalPages,
	};
}

export async function getPublishJob(ownerId, jobId, req = null) {
	const job = await loadOwnedPublishJob(ownerId, jobId, req);
	return mapPublishJob(job);
}

export async function retryPublishJob(ownerId, jobId, req = null) {
	const job = await loadOwnedPublishJob(ownerId, jobId, req);
	if (!['failed', 'cancelled'].includes(job.status)) {
		throw httpError(400, 'Only failed or cancelled jobs can be retried', 'INVALID_STATUS');
	}
	const updated = await pocketbaseClient.collection('publish_jobs').update(job.id, {
		status: 'queued',
		progress: 0,
		dead_letter: false,
		last_error: '',
		next_retry_at: '',
		claim_token: '',
		attempt_count: 0,
	});
	return mapPublishJob(updated);
}

export async function cancelPublishJob(ownerId, jobId, req = null) {
	const job = await loadOwnedPublishJob(ownerId, jobId, req);
	if (job.status === 'publishing') {
		throw httpError(409, 'Job is already publishing and cannot be cancelled', 'JOB_PUBLISHING');
	}
	if (['published', 'cancelled'].includes(job.status)) {
		throw httpError(400, 'Job cannot be cancelled', 'INVALID_STATUS');
	}
	const updated = await pocketbaseClient.collection('publish_jobs').update(job.id, {
		status: 'cancelled',
		completed_at: new Date().toISOString(),
		last_error: 'Cancelled by user',
	});
	if (job.article_id) {
		await syncArticleToDraftOnPublishAbort(job.article_id).catch(() => null);
	}
	return mapPublishJob(updated);
}

export async function listPublishHistory(ownerId, query = {}, req = null) {
	const page = Math.max(1, Number(query.page) || 1);
	const perPage = Math.min(100, Math.max(1, Number(query.perPage) || 20));
	const result = await pocketbaseClient.collection('publish_history').getList(page, perPage, {
		filter: buildOwnerScopedFilter(ownerId, req),
		sort: '-created',
		requestKey: null,
	}).catch(() => ({ items: [], page: 1, perPage, totalItems: 0, totalPages: 0 }));

	return {
		items: result.items.map(mapPublishHistory),
		page: result.page,
		perPage: result.perPage,
		totalItems: result.totalItems,
		totalPages: result.totalPages,
	};
}

export async function writePublishHistory({
	ownerId,
	workspaceKey,
	workspaceId,
	siteId,
	jobId,
	title,
	wpStatus,
	result,
	wpPostId,
	publishedUrl,
	publishedAt,
	durationMs,
	error,
	meta = {},
}) {
	return pocketbaseClient.collection('publish_history').create({
		owner: ownerId,
		workspace: workspaceId || undefined,
		workspace_key: workspaceKey || '',
		site: siteId,
		job: jobId,
		title,
		wp_status: wpStatus,
		result,
		wp_post_id: wpPostId || 0,
		published_url: publishedUrl || '',
		published_at: publishedAt || new Date().toISOString(),
		duration_ms: durationMs || 0,
		error: error || '',
		meta,
	}).catch(() => null);
}

export async function getWordpressPublishAnalytics(ownerId, query = {}, req = null) {
	const siteId = String(query.siteId || '').trim();
	const siteFilter = siteId
		? pocketbaseClient.filter('site = {:site}', { site: siteId })
		: '';
	const historyFilter = buildOwnerScopedFilter(ownerId, req, siteFilter);
	const jobsFilter = buildOwnerScopedFilter(ownerId, req, siteFilter);

	const [history, jobs, failedJobRows] = await Promise.all([
		pocketbaseClient.collection('publish_history').getFullList({
			filter: historyFilter,
			requestKey: null,
		}).catch(() => []),
		pocketbaseClient.collection('publish_jobs').getList(1, 1, {
			filter: jobsFilter,
			requestKey: null,
		}).catch(() => ({ totalItems: 0 })),
		pocketbaseClient.collection('publish_jobs').getFullList({
			filter: `${jobsFilter} && status = "failed"`,
			requestKey: null,
		}).catch(() => []),
	]);

	const rollup = rollupWordpressPublishAnalytics(history, failedJobRows);

	return {
		...rollup,
		jobs: Number(jobs.totalItems) || 0,
		history: history.slice(0, 25).map(mapPublishHistory),
	};
}
